import { NextResponse } from 'next/server';
import { z } from 'zod';
import { requireAdminApi } from '@/lib/auth';
import { getPrisma } from '@/lib/prisma';
import { DEFAULT_SERVICE_SETTINGS, planningServiceWeek, serviceWeeksForMonth } from '@/lib/service';
import { serializeWeeklyService } from '@/lib/weekly-service-data';

export const runtime='nodejs';
const querySchema=z.object({reference:z.iso.datetime().optional(),month:z.string().regex(/^\d{4}-\d{2}$/).optional()});

export async function GET(request:Request){if(!(await requireAdminApi()))return NextResponse.json({error:'Nepřihlášený přístup.'},{status:401});try{const url=new URL(request.url),input=querySchema.parse({reference:url.searchParams.get('reference')??undefined,month:url.searchParams.get('month')??undefined}),prisma=getPrisma(),settings=await prisma.settings.findUnique({where:{id:'default'}}),rules=settings?{weekStartDay:settings.weekStartDay,weekStartHour:settings.weekStartHour,weekEndDay:settings.weekEndDay,weekEndHour:settings.weekEndHour,minimumDt:settings.minimumDt,timezone:settings.timezone}:DEFAULT_SERVICE_SETTINGS,include={assignments:{orderBy:[{role:'asc' as const},{slot:'asc' as const}]},replacements:{include:{originalMember:true,replacementMember:true},orderBy:{from:'asc' as const}},temporaryAssignments:{include:{member:true},orderBy:[{from:'asc' as const},{role:'asc' as const},{slot:'asc' as const}]}};if(input.month){const intervals=serviceWeeksForMonth(input.month,rules),starts=intervals.map(item=>item.start),services=await prisma.weeklyService.findMany({where:{weekStart:{in:starts}},include,orderBy:{weekStart:'asc'}});return NextResponse.json({services:services.map(serializeWeeklyService),intervals:intervals.map(item=>({from:item.start.toISOString(),to:item.end.toISOString()}))});}const interval=planningServiceWeek(input.reference?new Date(input.reference):new Date(),rules),service=await prisma.weeklyService.findUnique({where:{weekStart:interval.start},include});return NextResponse.json({service:service?serializeWeeklyService(service):null,interval:{from:interval.start.toISOString(),to:interval.end.toISOString()}});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Služby se nepodařilo načíst.'},{status:400});}}
