import { NextResponse } from "next/server";
import { z } from "zod";
import { requireAdminApi } from "@/lib/auth";
import { getPrisma } from "@/lib/prisma";
import { serializeShoppingItem, shoppingItemInputSchema } from "@/lib/shopping";

export const runtime = "nodejs";
const patchSchema = shoppingItemInputSchema.partial().extend({ status: z.enum(["PLANNED", "PURCHASED"]).optional(), purchasedPrice: z.number().int().min(0).nullable().optional() }).superRefine((value, context) => { if (value.status === "PURCHASED" && value.purchasedPrice == null) context.addIssue({ code: "custom", path: ["purchasedPrice"], message: "Skutečná nákupní cena je povinná." }); });
const date = (value: string | null | undefined) => value ? new Date(`${value}T12:00:00Z`) : null;
const todayInPrague = () => date(new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/Prague", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date()));
export async function PATCH(request: Request, context: { params: Promise<{ id: string }> }) { if (!(await requireAdminApi())) return NextResponse.json({ error: "Nepřihlášený přístup." }, { status: 401 }); try { const { id } = await context.params, input = patchSchema.parse(await request.json()), prisma = getPrisma(), previous = await prisma.shoppingItem.findUnique({ where: { id } }); if (!previous) return NextResponse.json({ error: "Položka nebyla nalezena." }, { status: 404 }); const nextStatus = input.status ?? previous.status, action = previous.status !== nextStatus ? nextStatus === "PURCHASED" ? "SHOPPING_ITEM_PURCHASED" : "SHOPPING_ITEM_REOPENED" : "SHOPPING_ITEM_UPDATED"; const item = await prisma.$transaction(async (tx) => { const updated = await tx.shoppingItem.update({ where: { id }, data: { ...(input.name !== undefined && { name: input.name }), ...(input.estimatedPrice !== undefined && { estimatedPrice: input.estimatedPrice }), ...(input.purchaseDeadline !== undefined && { purchaseDeadline: date(input.purchaseDeadline) }), ...(input.store !== undefined && { store: input.store || null }), ...(input.url !== undefined && { url: input.url || null }), ...(input.note !== undefined && { note: input.note || null }), ...(input.status !== undefined && { status: input.status, purchasedAt: input.status === "PURCHASED" ? todayInPrague() : null, purchasedPrice: input.status === "PURCHASED" ? input.purchasedPrice : null }) } }); await tx.auditLog.create({ data: { action, entity: "ShoppingItem", entityId: id, description: action === "SHOPPING_ITEM_PURCHASED" ? `Položka ${updated.name} byla označena jako zakoupená za ${updated.purchasedPrice} Kč.` : action === "SHOPPING_ITEM_REOPENED" ? `Položka ${updated.name} byla vrácena do plánu; datum a skutečná cena nákupu byly odstraněny.` : `Položka ${updated.name} byla upravena.`, actor: "Administrátor" } }); return updated; }); return NextResponse.json({ item: serializeShoppingItem(item) }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Položku se nepodařilo upravit." }, { status: 400 }); } }
export async function DELETE(_request: Request, context: { params: Promise<{ id: string }> }) { if (!(await requireAdminApi())) return NextResponse.json({ error: "Nepřihlášený přístup." }, { status: 401 }); const { id } = await context.params, prisma = getPrisma(), item = await prisma.shoppingItem.findUnique({ where: { id } }); if (!item) return NextResponse.json({ error: "Položka nebyla nalezena." }, { status: 404 }); await prisma.$transaction([prisma.shoppingItem.delete({ where: { id } }), prisma.auditLog.create({ data: { action: "SHOPPING_ITEM_DELETED", entity: "ShoppingItem", entityId: id, description: `Položka ${item.name} byla odstraněna.`, actor: "Administrátor" } })]); return NextResponse.json({ ok: true }); }
