import { NextResponse } from 'next/server';
import { requireAdminApi } from '@/lib/auth';
import { parseActivityDate } from '@/lib/conditioning';
import { driverActivityInputSchema, nullable, serializeDriverActivity } from '@/lib/conditioning-data';
import { getPrisma } from '@/lib/prisma';

export const runtime='nodejs';
export async function PATCH(request:Request,context:{params:Promise<{id:string}>}){if(!(await requireAdminApi()))return NextResponse.json({error:'Nepřihlášený přístup.'},{status:401});try{const {id}=await context.params,input=driverActivityInputSchema.parse(await request.json()),prisma=getPrisma();const activity=await prisma.$transaction(async tx=>{const member=await tx.member.findUnique({where:{id:input.memberId},select:{canDrive:true,active:true,systemAccount:true}});if(!member?.active||!member.canDrive||member.systemAccount)throw new Error('Jízdu lze zapsat pouze aktivnímu strojníkovi.');const updated=await tx.driverActivity.update({where:{id},data:{memberId:input.memberId,date:parseActivityDate(input.date),type:input.type,vehicle:input.vehicle,kilometers:input.kilometers,incidentReference:nullable(input.incidentReference),note:nullable(input.note)}});await tx.auditLog.create({data:{action:'UPDATE',entity:'DriverActivity',entityId:id,description:'Jízda strojníka byla upravena.',actor:'Administrátor'}});return updated;});return NextResponse.json({activity:serializeDriverActivity(activity)});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Jízdu se nepodařilo upravit.'},{status:400});}}
export async function DELETE(_request:Request,context:{params:Promise<{id:string}>}){if(!(await requireAdminApi()))return NextResponse.json({error:'Nepřihlášený přístup.'},{status:401});const {id}=await context.params,prisma=getPrisma();await prisma.$transaction([prisma.driverActivity.delete({where:{id}}),prisma.auditLog.create({data:{action:'DELETE',entity:'DriverActivity',entityId:id,description:'Jízda strojníka byla odstraněna.',actor:'Administrátor'}})]);return NextResponse.json({ok:true});}
