import { NextResponse } from 'next/server';
import { z } from 'zod';
import { requireAdminApi } from '@/lib/auth';
import { getPrisma } from '@/lib/prisma';
import { DEFAULT_SERVICE_SETTINGS, serviceWeeksForMonth, validateServiceForConfirmation, type Assignment, type Candidate, type Role } from '@/lib/service';
import { serializeWeeklyService } from '@/lib/weekly-service-data';
import { syncServiceReplacements } from '@/lib/service-replacements-server';

export const runtime='nodejs';
const schema=z.object({month:z.string().regex(/^\d{4}-\d{2}$/)});
const candidate=(member:{id:string;firstName:string;lastName:string;active:boolean;systemAccount:boolean;reserveOnly:boolean;dt:boolean;medicalExamAt:Date|null;medicalValidUntil:Date|null;canCommand:boolean;canDrive:boolean;canFight:boolean;unavailability:{from:Date;to:Date}[]}):Candidate=>({id:member.id,name:`${member.firstName} ${member.lastName==='—'?'':member.lastName}`.trim(),active:member.active,system:member.systemAccount,reserveOnly:member.reserveOnly,dt:member.dt,medicalExam:member.medicalExamAt,medicalValidUntil:member.medicalValidUntil,roles:[member.canCommand&&'COMMANDER',member.canDrive&&'DRIVER',member.canFight&&'FIREFIGHTER'].filter(Boolean) as Role[],serviceCount:0,lastService:null,unavailable:member.unavailability});

export async function POST(request:Request){if(!(await requireAdminApi()))return NextResponse.json({error:'Nepřihlášený přístup.'},{status:401});try{const {month}=schema.parse(await request.json()),prisma=getPrisma(),settings=await prisma.settings.findUnique({where:{id:'default'}}),rules=settings?{weekStartDay:settings.weekStartDay,weekStartHour:settings.weekStartHour,weekEndDay:settings.weekEndDay,weekEndHour:settings.weekEndHour,minimumDt:settings.minimumDt,timezone:settings.timezone}:DEFAULT_SERVICE_SETTINGS,intervals=serviceWeeksForMonth(month,rules),services=await prisma.weeklyService.findMany({where:{weekStart:{in:intervals.map(item=>item.start)},status:'DRAFT'},include:{assignments:{include:{member:{include:{unavailability:true}}},orderBy:[{role:'asc'},{slot:'asc'}]}}}),confirmed:string[]=[],errors:{id:string;from:string;error:string}[]=[];for(const service of services){const assignments:Assignment[]=service.assignments.map(item=>({role:item.role as Role,member:candidate(item.member),mode:item.selectionMode})),validation=validateServiceForConfirmation(assignments,service.weekStart,service.weekEnd,rules.minimumDt);if(!validation.valid){errors.push({id:service.id,from:service.weekStart.toISOString(),error:validation.errors.join('\n')});continue;}const replacements=await syncServiceReplacements(service.id),missing=replacements.filter(item=>!item.valid);if(missing.length){errors.push({id:service.id,from:service.weekStart.toISOString(),error:missing.map(item=>`${item.from.toISOString()} – ${item.issue}`).join('\n')});continue;}await prisma.$transaction([prisma.weeklyService.update({where:{id:service.id},data:{status:'CONFIRMED',confirmedAt:new Date()}}),prisma.auditLog.create({data:{action:'WEEK_CONFIRMED',entity:'WeeklyService',entityId:service.id,description:'Týdenní posádka byla potvrzena v měsíčním plánu.',actor:'Administrátor'}})]);confirmed.push(service.id);}await prisma.auditLog.create({data:{action:'MONTH_PLAN_CONFIRMED',entity:'MonthlyPlan',entityId:month,description:`Hromadně potvrzeno ${confirmed.length} platných služeb, neplatných ${errors.length}.`,actor:'Administrátor'}});const updated=await prisma.weeklyService.findMany({where:{weekStart:{in:intervals.map(item=>item.start)}},include:{assignments:{orderBy:[{role:'asc'},{slot:'asc'}]},replacements:{include:{originalMember:true,replacementMember:true},orderBy:{from:'asc'}}},orderBy:{weekStart:'asc'}});return NextResponse.json({services:updated.map(serializeWeeklyService),confirmed:confirmed.length,errors});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Služby se nepodařilo potvrdit.'},{status:400});}}
