import { NextResponse } from 'next/server';
import { z } from 'zod';
import { requireAdminApi } from '@/lib/auth';
import { getPrisma } from '@/lib/prisma';
import { eligibility, intervalsOverlap, recurringOccurrences, type Candidate, type Role } from '@/lib/service';
import { formatCzechDate, roleLabels } from '@/lib/member-data';

export const runtime='nodejs';
const query=z.object({role:z.enum(['COMMANDER','DRIVER','FIREFIGHTER'])});
export async function GET(request:Request,context:{params:Promise<{id:string}>}){if(!(await requireAdminApi()))return NextResponse.json({error:'Nepřihlášený přístup.'},{status:401});try{const {id}=await context.params,{role}=query.parse({role:new URL(request.url).searchParams.get('role')}),prisma=getPrisma(),[service,members]=await Promise.all([prisma.weeklyService.findUnique({where:{id}}),prisma.member.findMany({include:{unavailability:true,recurringUnavailability:{where:{active:true}}}})]);if(!service)return NextResponse.json({error:'Služba nebyla nalezena.'},{status:404});const candidates=members.map(member=>{const value:Candidate={id:member.id,name:`${member.firstName} ${member.lastName==='—'?'':member.lastName}`.trim(),active:member.active,system:member.systemAccount,reserveOnly:member.reserveOnly,dt:member.dt,medicalExam:member.medicalExamAt,medicalValidUntil:member.medicalValidUntil,roles:[member.canCommand&&'COMMANDER',member.canDrive&&'DRIVER',member.canFight&&'FIREFIGHTER'].filter(Boolean) as Role[],serviceCount:0,lastService:null,unavailable:member.unavailability};const reasons=eligibility(value,role,service.weekStart,service.weekEnd,true).reasons;if(member.unavailability.some(item=>intervalsOverlap(item.from,item.to,service.weekStart,service.weekEnd)))reasons.push('Nedostupný – běžná nedostupnost zasahuje do služby');const occurrences=member.recurringUnavailability.flatMap(rule=>recurringOccurrences({anchorStart:rule.anchorStart,durationMinutes:rule.durationMinutes,intervalMinutes:rule.intervalMinutes},service.weekStart,service.weekEnd));return{id:member.id,name:value.name,primaryRole:roleLabels()[member.primaryRole],permissions:[member.canCommand&&'Velitel',member.canDrive&&'Strojník',member.canFight&&'Hasič'].filter(Boolean),dt:member.dt,medicalValidUntil:formatCzechDate(member.medicalValidUntil),available:reasons.length===0,warnings:[...new Set([...reasons,...(occurrences.length?[`Pracovní směna 24/48: ${occurrences.length} intervalů se záskokem`]:[])])]};}).sort((a,b)=>Number(b.available)-Number(a.available)||a.name.localeCompare(b.name,'cs'));return NextResponse.json({candidates});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Kandidáty se nepodařilo načíst.'},{status:400});}}
