// Names and categories supplied by the unit; no methodology text is reproduced.
export const trainingTopicCatalog = [
  {
    name: 'Práce ve výšce a nad volnou hloubkou',
    category: 'Výkon služby',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'vykon-sluzby-prace-ve-vysce-a-nad-volnou-hloubkou',
    sortOrder: 0,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Normy znalostí – teze odborné přípravy',
    category: 'Výkon služby',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'vykon-sluzby-normy-znalosti-teze-odborne-pripravy',
    sortOrder: 1,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Pravidelná odborná příprava',
    category: 'Výkon služby',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'vykon-sluzby-pravidelna-odborna-priprava',
    sortOrder: 2,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Příprava taktických a prověřovacích cvičení',
    category: 'Výkon služby',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'vykon-sluzby-priprava-taktickych-a-proverovacich-cviceni',
    sortOrder: 3,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Právní předpisy v oblasti činnosti jednotek PO',
    category: 'Výkon služby',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'vykon-sluzby-pravni-predpisy-v-oblasti-cinnosti-jednotek-po',
    sortOrder: 4,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Úvod do problematiky právních předpisů',
    category: 'Výkon služby',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'vykon-sluzby-uvod-do-problematiky-pravnich-predpisu',
    sortOrder: 5,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Přehled předpisů pro jednotky PO',
    category: 'Výkon služby',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'vykon-sluzby-prehled-predpisu-pro-jednotky-po',
    sortOrder: 6,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Bojový řád jednotek požární ochrany',
    category: 'Bojový řád',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'bojovy-rad-bojovy-rad-jednotek-pozarni-ochrany',
    sortOrder: 7,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Požární zásah',
    category: 'Bojový řád',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'bojovy-rad-pozarni-zasah',
    sortOrder: 8,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Analýza vybraných požárů',
    category: 'Bojový řád',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'bojovy-rad-analyza-vybranych-pozaru',
    sortOrder: 9,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Požár rodinného domu',
    category: 'Bojový řád',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'bojovy-rad-pozar-rodinneho-domu',
    sortOrder: 10,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Požár bytu',
    category: 'Bojový řád',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'bojovy-rad-pozar-bytu',
    sortOrder: 11,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Požár osobního vozidla',
    category: 'Bojový řád',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'bojovy-rad-pozar-osobniho-vozidla',
    sortOrder: 12,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Požár vozidel s alternativním pohonem',
    category: 'Bojový řád',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'bojovy-rad-pozar-vozidel-s-alternativnim-pohonem',
    sortOrder: 13,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Požár dopravních prostředků',
    category: 'Bojový řád',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'bojovy-rad-pozar-dopravnich-prostredku',
    sortOrder: 14,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Požár cisterny s hořlavou kapalinou',
    category: 'Bojový řád',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'bojovy-rad-pozar-cisterny-s-horlavou-kapalinou',
    sortOrder: 15,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Požár tlakových láhví',
    category: 'Bojový řád',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'bojovy-rad-pozar-tlakovych-lahvi',
    sortOrder: 16,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Požár v suterénních prostorech',
    category: 'Bojový řád',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'bojovy-rad-pozar-v-suterennich-prostorech',
    sortOrder: 17,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Požáry střech',
    category: 'Bojový řád',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'bojovy-rad-pozary-strech',
    sortOrder: 18,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Požáry v přírodním prostředí',
    category: 'Bojový řád',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'bojovy-rad-pozary-v-prirodnim-prostredi',
    sortOrder: 19,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Požáry na volném prostranství',
    category: 'Bojový řád',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'bojovy-rad-pozary-na-volnem-prostranstvi',
    sortOrder: 20,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Cvičební řád jednotek požární ochrany',
    category: 'Cvičební řád',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'cvicebni-rad-cvicebni-rad-jednotek-pozarni-ochrany',
    sortOrder: 21,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Základní činnosti družstva',
    category: 'Cvičební řád',
    sourceType: 'INTERNAL',
    code: 'cvicebni-rad-zakladni-cinnosti-druzstva',
    sortOrder: 22,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Nástupy a organizace družstva',
    category: 'Cvičební řád',
    sourceType: 'INTERNAL',
    code: 'cvicebni-rad-nastupy-a-organizace-druzstva',
    sortOrder: 23,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Práce s hadicovým vedením',
    category: 'Cvičební řád',
    sourceType: 'INTERNAL',
    code: 'cvicebni-rad-prace-s-hadicovym-vedenim',
    sortOrder: 24,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Práce s proudnicemi',
    category: 'Cvičební řád',
    sourceType: 'INTERNAL',
    code: 'cvicebni-rad-prace-s-proudnicemi',
    sortOrder: 25,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Práce s armaturami',
    category: 'Cvičební řád',
    sourceType: 'INTERNAL',
    code: 'cvicebni-rad-prace-s-armaturami',
    sortOrder: 26,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Práce s žebříky',
    category: 'Cvičební řád',
    sourceType: 'INTERNAL',
    code: 'cvicebni-rad-prace-s-zebriky',
    sortOrder: 27,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Práce s požární technikou',
    category: 'Cvičební řád',
    sourceType: 'INTERNAL',
    code: 'cvicebni-rad-prace-s-pozarni-technikou',
    sortOrder: 28,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Praktický výcvik jednotky',
    category: 'Cvičební řád',
    sourceType: 'INTERNAL',
    code: 'cvicebni-rad-prakticky-vycvik-jednotky',
    sortOrder: 29,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Úvod do problematiky dálkové dopravy vody',
    category: 'Dálková doprava vody',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dalkova-doprava-vody-uvod-do-problematiky-dalkove-dopravy-vody',
    sortOrder: 30,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Druhy dálkové dopravy vody',
    category: 'Dálková doprava vody',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dalkova-doprava-vody-druhy-dalkove-dopravy-vody',
    sortOrder: 31,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'DDV kyvadlovým způsobem – požární technika a prostředky',
    category: 'Dálková doprava vody',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dalkova-doprava-vody-ddv-kyvadlovym-zpusobem-pozarni-technika-a-prostredky',
    sortOrder: 32,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'DDV hadicovým vedením – požární technika, prostředky a taktika',
    category: 'Dálková doprava vody',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dalkova-doprava-vody-ddv-hadicovym-vedenim-pozarni-technika-prostredky-a-taktika',
    sortOrder: 33,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'DDV kyvadlovým způsobem – taktické postupy a nebezpečí',
    category: 'Dálková doprava vody',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dalkova-doprava-vody-ddv-kyvadlovym-zpusobem-takticke-postupy-a-nebezpeci',
    sortOrder: 34,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'DDV hadicovým vedením – taktické postupy a nebezpečí',
    category: 'Dálková doprava vody',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dalkova-doprava-vody-ddv-hadicovym-vedenim-takticke-postupy-a-nebezpeci',
    sortOrder: 35,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Alternativní způsoby DDV',
    category: 'Dálková doprava vody',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dalkova-doprava-vody-alternativni-zpusoby-ddv',
    sortOrder: 36,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Dálková doprava kyvadlovým způsobem – určení Ncas',
    category: 'Dálková doprava vody',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dalkova-doprava-vody-dalkova-doprava-kyvadlovym-zpusobem-urceni-ncas',
    sortOrder: 37,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Dálková doprava hadicovým vedením – určení ztrát a Nč',
    category: 'Dálková doprava vody',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dalkova-doprava-vody-dalkova-doprava-hadicovym-vedenim-urceni-ztrat-a-nc',
    sortOrder: 38,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Určení převýšení',
    category: 'Dálková doprava vody',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dalkova-doprava-vody-urceni-prevyseni',
    sortOrder: 39,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Určení vzdálenosti',
    category: 'Dálková doprava vody',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dalkova-doprava-vody-urceni-vzdalenosti',
    sortOrder: 40,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Orientace v mapách',
    category: 'Dálková doprava vody',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dalkova-doprava-vody-orientace-v-mapach',
    sortOrder: 41,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Praktické příklady dálkové dopravy vody',
    category: 'Dálková doprava vody',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dalkova-doprava-vody-prakticke-priklady-dalkove-dopravy-vody',
    sortOrder: 42,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Dokumentace zdolávání požáru',
    category: 'Dokumentace zdolávání požáru',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dokumentace-zdolavani-pozaru-dokumentace-zdolavani-pozaru',
    sortOrder: 43,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Výpočet sil a prostředků',
    category: 'Dokumentace zdolávání požáru',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dokumentace-zdolavani-pozaru-vypocet-sil-a-prostredku',
    sortOrder: 44,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Úvod do problematiky',
    category: 'Dokumentace zdolávání požáru',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dokumentace-zdolavani-pozaru-uvod-do-problematiky',
    sortOrder: 45,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Pojmy, veličiny a definice',
    category: 'Dokumentace zdolávání požáru',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dokumentace-zdolavani-pozaru-pojmy-veliciny-a-definice',
    sortOrder: 46,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Výpočet SaP pro hašení vodou – určení Tvr',
    category: 'Dokumentace zdolávání požáru',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dokumentace-zdolavani-pozaru-vypocet-sap-pro-haseni-vodou-urceni-tvr',
    sortOrder: 47,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Výpočet SaP pro hašení vodou – určení t1, t2, t3',
    category: 'Dokumentace zdolávání požáru',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dokumentace-zdolavani-pozaru-vypocet-sap-pro-haseni-vodou-urceni-t1-t2-t3',
    sortOrder: 48,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Výpočet SaP pro hašení vodou – určení Rpož',
    category: 'Dokumentace zdolávání požáru',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dokumentace-zdolavani-pozaru-vypocet-sap-pro-haseni-vodou-urceni-rpoz',
    sortOrder: 49,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Výpočet SaP pro hašení vodou – určení Sp a Sh',
    category: 'Dokumentace zdolávání požáru',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dokumentace-zdolavani-pozaru-vypocet-sap-pro-haseni-vodou-urceni-sp-a-sh',
    sortOrder: 50,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Výpočet SaP pro hašení vodou – určení Qp a Npr',
    category: 'Dokumentace zdolávání požáru',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dokumentace-zdolavani-pozaru-vypocet-sap-pro-haseni-vodou-urceni-qp-a-npr',
    sortOrder: 51,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Výpočet SaP pro hašení vodou – určení Nha a Na',
    category: 'Dokumentace zdolávání požáru',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dokumentace-zdolavani-pozaru-vypocet-sap-pro-haseni-vodou-urceni-nha-a-na',
    sortOrder: 52,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Výpočet SaP pro hašení pěnou – základní principy',
    category: 'Dokumentace zdolávání požáru',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dokumentace-zdolavani-pozaru-vypocet-sap-pro-haseni-penou-zakladni-principy',
    sortOrder: 53,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Výpočet SaP pro hašení pěnou – určení Sh, Npr, Qph, Qpo',
    category: 'Dokumentace zdolávání požáru',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dokumentace-zdolavani-pozaru-vypocet-sap-pro-haseni-penou-urceni-sh-npr-qph-qpo',
    sortOrder: 54,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Plošné pokrytí jednotkami PO',
    category: 'Organizace požární ochrany',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'organizace-pozarni-ochrany-plosne-pokryti-jednotkami-po',
    sortOrder: 55,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Poplachový plán',
    category: 'Organizace požární ochrany',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'organizace-pozarni-ochrany-poplachovy-plan',
    sortOrder: 56,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Stupně požárního poplachu',
    category: 'Organizace požární ochrany',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'organizace-pozarni-ochrany-stupne-pozarniho-poplachu',
    sortOrder: 57,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Organizace výjezdu jednotek',
    category: 'Organizace požární ochrany',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'organizace-pozarni-ochrany-organizace-vyjezdu-jednotek',
    sortOrder: 58,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Tělesná příprava a sport',
    category: 'Tělesná příprava',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'telesna-priprava-telesna-priprava-a-sport',
    sortOrder: 59,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'TFA',
    category: 'Tělesná příprava',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'telesna-priprava-tfa',
    sortOrder: 60,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Požární sport',
    category: 'Tělesná příprava',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'telesna-priprava-pozarni-sport',
    sortOrder: 61,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Vyprošťování u dopravních nehod',
    category: 'Vyprošťování u dopravních nehod',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'vyprostovani-u-dopravnich-nehod-vyprostovani-u-dopravnich-nehod',
    sortOrder: 62,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Vybrané dokumenty z oblasti VDN',
    category: 'Vyprošťování u dopravních nehod',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'vyprostovani-u-dopravnich-nehod-vybrane-dokumenty-z-oblasti-vdn',
    sortOrder: 63,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Informace z oblasti VDN',
    category: 'Vyprošťování u dopravních nehod',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'vyprostovani-u-dopravnich-nehod-informace-z-oblasti-vdn',
    sortOrder: 64,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Příručky pro záchranáře',
    category: 'Vyprošťování u dopravních nehod',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'vyprostovani-u-dopravnich-nehod-prirucky-pro-zachranare',
    sortOrder: 65,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Soutěže ve vyprošťování',
    category: 'Vyprošťování u dopravních nehod',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'vyprostovani-u-dopravnich-nehod-souteze-ve-vyprostovani',
    sortOrder: 66,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Kurz Instruktor VDN',
    category: 'Vyprošťování u dopravních nehod',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'vyprostovani-u-dopravnich-nehod-kurz-instruktor-vdn',
    sortOrder: 67,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Vyprošťování osob z vozidel – SDH',
    category: 'Vyprošťování u dopravních nehod',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'vyprostovani-u-dopravnich-nehod-vyprostovani-osob-z-vozidel-sdh',
    sortOrder: 68,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Zajištění místa dopravní nehody',
    category: 'Vyprošťování u dopravních nehod',
    sourceType: 'INTERNAL',
    code: 'vyprostovani-u-dopravnich-nehod-zajisteni-mista-dopravni-nehody',
    sortOrder: 69,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Stabilizace vozidla',
    category: 'Vyprošťování u dopravních nehod',
    sourceType: 'INTERNAL',
    code: 'vyprostovani-u-dopravnich-nehod-stabilizace-vozidla',
    sortOrder: 70,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Odpojení akumulátoru',
    category: 'Vyprošťování u dopravních nehod',
    sourceType: 'INTERNAL',
    code: 'vyprostovani-u-dopravnich-nehod-odpojeni-akumulatoru',
    sortOrder: 71,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Airbagy a bezpečnostní systémy',
    category: 'Vyprošťování u dopravních nehod',
    sourceType: 'INTERNAL',
    code: 'vyprostovani-u-dopravnich-nehod-airbagy-a-bezpecnostni-systemy',
    sortOrder: 72,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Hydraulické vyprošťovací zařízení',
    category: 'Vyprošťování u dopravních nehod',
    sourceType: 'INTERNAL',
    code: 'vyprostovani-u-dopravnich-nehod-hydraulicke-vyprostovaci-zarizeni',
    sortOrder: 73,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Odstranění dveří',
    category: 'Vyprošťování u dopravních nehod',
    sourceType: 'INTERNAL',
    code: 'vyprostovani-u-dopravnich-nehod-odstraneni-dveri',
    sortOrder: 74,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Odstranění střechy',
    category: 'Vyprošťování u dopravních nehod',
    sourceType: 'INTERNAL',
    code: 'vyprostovani-u-dopravnich-nehod-odstraneni-strechy',
    sortOrder: 75,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Vytvoření prostoru pro záchranu',
    category: 'Vyprošťování u dopravních nehod',
    sourceType: 'INTERNAL',
    code: 'vyprostovani-u-dopravnich-nehod-vytvoreni-prostoru-pro-zachranu',
    sortOrder: 76,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Spolupráce se ZZS',
    category: 'Vyprošťování u dopravních nehod',
    sourceType: 'INTERNAL',
    code: 'vyprostovani-u-dopravnich-nehod-spoluprace-se-zzs',
    sortOrder: 77,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Transport pacienta',
    category: 'Vyprošťování u dopravních nehod',
    sourceType: 'INTERNAL',
    code: 'vyprostovani-u-dopravnich-nehod-transport-pacienta',
    sortOrder: 78,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Práce na vodě',
    category: 'Práce na vodě a ledu',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'prace-na-vode-a-ledu-prace-na-vode',
    sortOrder: 79,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Práce na ledu',
    category: 'Práce na vodě a ledu',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'prace-na-vode-a-ledu-prace-na-ledu',
    sortOrder: 80,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Záchrana osoby z vody',
    category: 'Práce na vodě a ledu',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'prace-na-vode-a-ledu-zachrana-osoby-z-vody',
    sortOrder: 81,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Záchrana osoby z ledu',
    category: 'Práce na vodě a ledu',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'prace-na-vode-a-ledu-zachrana-osoby-z-ledu',
    sortOrder: 82,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Práce na vodě pro členy dobrovolných jednotek PO',
    category: 'Práce na vodě a ledu',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'prace-na-vode-a-ledu-prace-na-vode-pro-cleny-dobrovolnych-jednotek-po',
    sortOrder: 83,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Zařízení simulující reálné podmínky požáru',
    category: 'Dýchací technika',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dychaci-technika-zarizeni-simulujici-realne-podminky-pozaru',
    sortOrder: 84,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'NDT-16',
    category: 'Dýchací technika',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dychaci-technika-ndt-16',
    sortOrder: 85,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Použití izolačního dýchacího přístroje',
    category: 'Dýchací technika',
    sourceType: 'INTERNAL',
    code: 'dychaci-technika-pouziti-izolacniho-dychaciho-pristroje',
    sortOrder: 86,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Bezpečnost při použití DT',
    category: 'Dýchací technika',
    sourceType: 'INTERNAL',
    code: 'dychaci-technika-bezpecnost-pri-pouziti-dt',
    sortOrder: 87,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Kontrola DT před použitím',
    category: 'Dýchací technika',
    sourceType: 'INTERNAL',
    code: 'dychaci-technika-kontrola-dt-pred-pouzitim',
    sortOrder: 88,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Činnost nositele DT',
    category: 'Dýchací technika',
    sourceType: 'INTERNAL',
    code: 'dychaci-technika-cinnost-nositele-dt',
    sortOrder: 89,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Nouzové situace při použití DT',
    category: 'Dýchací technika',
    sourceType: 'INTERNAL',
    code: 'dychaci-technika-nouzove-situace-pri-pouziti-dt',
    sortOrder: 90,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Pohyb v zakouřeném prostoru',
    category: 'Dýchací technika',
    sourceType: 'INTERNAL',
    code: 'dychaci-technika-pohyb-v-zakourenem-prostoru',
    sortOrder: 91,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Vyhledávání osob v zakouřeném prostoru',
    category: 'Dýchací technika',
    sourceType: 'INTERNAL',
    code: 'dychaci-technika-vyhledavani-osob-v-zakourenem-prostoru',
    sortOrder: 92,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'První pomoc',
    category: 'První pomoc',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'prvni-pomoc-prvni-pomoc',
    sortOrder: 93,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Základy zdravotnických znalostí pro členy dobrovolných jednotek PO',
    category: 'První pomoc',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'prvni-pomoc-zaklady-zdravotnickych-znalosti-pro-cleny-dobrovolnych-jednotek-po',
    sortOrder: 94,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Bezvědomí',
    category: 'První pomoc',
    sourceType: 'INTERNAL',
    code: 'prvni-pomoc-bezvedomi',
    sortOrder: 95,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Kontrola životních funkcí',
    category: 'První pomoc',
    sourceType: 'INTERNAL',
    code: 'prvni-pomoc-kontrola-zivotnich-funkci',
    sortOrder: 96,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'KPR',
    category: 'První pomoc',
    sourceType: 'INTERNAL',
    code: 'prvni-pomoc-kpr',
    sortOrder: 97,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'AED',
    category: 'První pomoc',
    sourceType: 'INTERNAL',
    code: 'prvni-pomoc-aed',
    sortOrder: 98,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Masivní krvácení',
    category: 'První pomoc',
    sourceType: 'INTERNAL',
    code: 'prvni-pomoc-masivni-krvaceni',
    sortOrder: 99,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Šok',
    category: 'První pomoc',
    sourceType: 'INTERNAL',
    code: 'prvni-pomoc-sok',
    sortOrder: 100,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Popáleniny',
    category: 'První pomoc',
    sourceType: 'INTERNAL',
    code: 'prvni-pomoc-popaleniny',
    sortOrder: 101,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Trauma',
    category: 'První pomoc',
    sourceType: 'INTERNAL',
    code: 'prvni-pomoc-trauma',
    sortOrder: 102,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Úrazy',
    category: 'První pomoc',
    sourceType: 'INTERNAL',
    code: 'prvni-pomoc-urazy',
    sortOrder: 103,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Fixace pacienta',
    category: 'První pomoc',
    sourceType: 'INTERNAL',
    code: 'prvni-pomoc-fixace-pacienta',
    sortOrder: 104,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Transport pacienta',
    category: 'První pomoc',
    sourceType: 'INTERNAL',
    code: 'prvni-pomoc-transport-pacienta',
    sortOrder: 105,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Spolupráce se ZZS',
    category: 'První pomoc',
    sourceType: 'INTERNAL',
    code: 'prvni-pomoc-spoluprace-se-zzs',
    sortOrder: 106,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Obsluha motorových řetězových pil',
    category: 'Motorové pily',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'motorove-pily-obsluha-motorovych-retezovych-pil',
    sortOrder: 107,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Obsluha rozbrušovacích pil',
    category: 'Motorové pily',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'motorove-pily-obsluha-rozbrusovacich-pil',
    sortOrder: 108,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Obsluha MP v jednotce PO',
    category: 'Motorové pily',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'motorove-pily-obsluha-mp-v-jednotce-po',
    sortOrder: 109,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'BOZP při práci s motorovou pilou',
    category: 'Motorové pily',
    sourceType: 'INTERNAL',
    code: 'motorove-pily-bozp-pri-praci-s-motorovou-pilou',
    sortOrder: 110,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Kontrola pily před použitím',
    category: 'Motorové pily',
    sourceType: 'INTERNAL',
    code: 'motorove-pily-kontrola-pily-pred-pouzitim',
    sortOrder: 111,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Kácení',
    category: 'Motorové pily',
    sourceType: 'INTERNAL',
    code: 'motorove-pily-kaceni',
    sortOrder: 112,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Odvětvování',
    category: 'Motorové pily',
    sourceType: 'INTERNAL',
    code: 'motorove-pily-odvetvovani',
    sortOrder: 113,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Řezání napruženého dřeva',
    category: 'Motorové pily',
    sourceType: 'INTERNAL',
    code: 'motorove-pily-rezani-napruzeneho-dreva',
    sortOrder: 114,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Odstraňování následků větru',
    category: 'Motorové pily',
    sourceType: 'INTERNAL',
    code: 'motorove-pily-odstranovani-nasledku-vetru',
    sortOrder: 115,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Rozbrušovací pila',
    category: 'Motorové pily',
    sourceType: 'INTERNAL',
    code: 'motorove-pily-rozbrusovaci-pila',
    sortOrder: 116,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Elektromobilita',
    category: 'Elektromobilita',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'elektromobilita-elektromobilita',
    sortOrder: 117,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Vozidla s alternativním pohonem',
    category: 'Elektromobilita',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'elektromobilita-vozidla-s-alternativnim-pohonem',
    sortOrder: 118,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Požár elektromobilu',
    category: 'Elektromobilita',
    sourceType: 'INTERNAL',
    code: 'elektromobilita-pozar-elektromobilu',
    sortOrder: 119,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Rizika trakčních baterií',
    category: 'Elektromobilita',
    sourceType: 'INTERNAL',
    code: 'elektromobilita-rizika-trakcnich-baterii',
    sortOrder: 120,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Bezpečné odpojení vozidla',
    category: 'Elektromobilita',
    sourceType: 'INTERNAL',
    code: 'elektromobilita-bezpecne-odpojeni-vozidla',
    sortOrder: 121,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Tepelný únik baterie',
    category: 'Elektromobilita',
    sourceType: 'INTERNAL',
    code: 'elektromobilita-tepelny-unik-baterie',
    sortOrder: 122,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Opětovné vznícení',
    category: 'Elektromobilita',
    sourceType: 'INTERNAL',
    code: 'elektromobilita-opetovne-vzniceni',
    sortOrder: 123,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Strojní služba',
    category: 'Strojní služba',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'strojni-sluzba-strojni-sluzba',
    sortOrder: 124,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Strojní služba u jednotek SDH obcí',
    category: 'Strojní služba',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'strojni-sluzba-strojni-sluzba-u-jednotek-sdh-obci',
    sortOrder: 125,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Technik strojní služby jednotky SDH obce',
    category: 'Strojní služba',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'strojni-sluzba-technik-strojni-sluzby-jednotky-sdh-obce',
    sortOrder: 126,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'T-STS JSDHO – 8 hod.',
    category: 'Strojní služba',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'strojni-sluzba-t-sts-jsdho-8-hod',
    sortOrder: 127,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'S-40',
    category: 'Strojní služba',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'strojni-sluzba-s-40',
    sortOrder: 128,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'S-16',
    category: 'Strojní služba',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'strojni-sluzba-s-16',
    sortOrder: 129,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'S-8',
    category: 'Strojní služba',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'strojni-sluzba-s-8',
    sortOrder: 130,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Obsluha CAS',
    category: 'Strojní služba',
    sourceType: 'INTERNAL',
    code: 'strojni-sluzba-obsluha-cas',
    sortOrder: 131,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Obsluha požárního čerpadla',
    category: 'Strojní služba',
    sourceType: 'INTERNAL',
    code: 'strojni-sluzba-obsluha-pozarniho-cerpadla',
    sortOrder: 132,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Zavodnění čerpadla',
    category: 'Strojní služba',
    sourceType: 'INTERNAL',
    code: 'strojni-sluzba-zavodneni-cerpadla',
    sortOrder: 133,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Sání z volného vodního zdroje',
    category: 'Strojní služba',
    sourceType: 'INTERNAL',
    code: 'strojni-sluzba-sani-z-volneho-vodniho-zdroje',
    sortOrder: 134,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Hydrantová síť',
    category: 'Strojní služba',
    sourceType: 'INTERNAL',
    code: 'strojni-sluzba-hydrantova-sit',
    sortOrder: 135,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Doprava vody',
    category: 'Strojní služba',
    sourceType: 'INTERNAL',
    code: 'strojni-sluzba-doprava-vody',
    sortOrder: 136,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Tlakové ztráty',
    category: 'Strojní služba',
    sourceType: 'INTERNAL',
    code: 'strojni-sluzba-tlakove-ztraty',
    sortOrder: 137,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Jízda k zásahu',
    category: 'Strojní služba',
    sourceType: 'INTERNAL',
    code: 'strojni-sluzba-jizda-k-zasahu',
    sortOrder: 138,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Jízda s právem přednostní jízdy',
    category: 'Strojní služba',
    sourceType: 'INTERNAL',
    code: 'strojni-sluzba-jizda-s-pravem-prednostni-jizdy',
    sortOrder: 139,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Couvání požární techniky',
    category: 'Strojní služba',
    sourceType: 'INTERNAL',
    code: 'strojni-sluzba-couvani-pozarni-techniky',
    sortOrder: 140,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Kondiční jízdy',
    category: 'Strojní služba',
    sourceType: 'INTERNAL',
    code: 'strojni-sluzba-kondicni-jizdy',
    sortOrder: 141,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Kontrola vozidla',
    category: 'Strojní služba',
    sourceType: 'INTERNAL',
    code: 'strojni-sluzba-kontrola-vozidla',
    sortOrder: 142,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Provozní kapaliny',
    category: 'Strojní služba',
    sourceType: 'INTERNAL',
    code: 'strojni-sluzba-provozni-kapaliny',
    sortOrder: 143,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Údržba požární techniky',
    category: 'Strojní služba',
    sourceType: 'INTERNAL',
    code: 'strojni-sluzba-udrzba-pozarni-techniky',
    sortOrder: 144,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Chemická služba',
    category: 'Chemická služba',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'chemicka-sluzba-chemicka-sluzba',
    sortOrder: 145,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Teorie hoření',
    category: 'Hasební látky',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'hasebni-latky-teorie-horeni',
    sortOrder: 146,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Teorie hašení',
    category: 'Hasební látky',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'hasebni-latky-teorie-haseni',
    sortOrder: 147,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Voda jako hasební látka',
    category: 'Hasební látky',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'hasebni-latky-voda-jako-hasebni-latka',
    sortOrder: 148,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Hasicí pěny',
    category: 'Hasební látky',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'hasebni-latky-hasici-peny',
    sortOrder: 149,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Hasicí prášky',
    category: 'Hasební látky',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'hasebni-latky-hasici-prasky',
    sortOrder: 150,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Inertní plyny',
    category: 'Hasební látky',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'hasebni-latky-inertni-plyny',
    sortOrder: 151,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Hasicí halony',
    category: 'Hasební látky',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'hasebni-latky-hasici-halony',
    sortOrder: 152,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Halonové alternativy a čistá hasiva',
    category: 'Hasební látky',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'hasebni-latky-halonove-alternativy-a-cista-hasiva',
    sortOrder: 153,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Jednoduché hasební prostředky',
    category: 'Hasební látky',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'hasebni-latky-jednoduche-hasebni-prostredky',
    sortOrder: 154,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Kultura a efektivita hašení',
    category: 'Hasební látky',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'hasebni-latky-kultura-a-efektivita-haseni',
    sortOrder: 155,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Nebezpečnost chemických látek',
    category: 'Nebezpečné látky',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'nebezpecne-latky-nebezpecnost-chemickych-latek',
    sortOrder: 156,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Úvod do problematiky nebezpečných chemických látek',
    category: 'Nebezpečné látky',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'nebezpecne-latky-uvod-do-problematiky-nebezpecnych-chemickych-latek',
    sortOrder: 157,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Legislativa nebezpečných látek',
    category: 'Nebezpečné látky',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'nebezpecne-latky-legislativa-nebezpecnych-latek',
    sortOrder: 158,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Zákon o chemických látkách',
    category: 'Nebezpečné látky',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'nebezpecne-latky-zakon-o-chemickych-latkach',
    sortOrder: 159,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Legislativa EU',
    category: 'Nebezpečné látky',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'nebezpecne-latky-legislativa-eu',
    sortOrder: 160,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Mezinárodní předpisy upravující přepravu',
    category: 'Nebezpečné látky',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'nebezpecne-latky-mezinarodni-predpisy-upravujici-prepravu',
    sortOrder: 161,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Skupiny nebezpečnosti',
    category: 'Nebezpečné látky',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'nebezpecne-latky-skupiny-nebezpecnosti',
    sortOrder: 162,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Označování nebezpečných látek',
    category: 'Nebezpečné látky',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'nebezpecne-latky-oznacovani-nebezpecnych-latek',
    sortOrder: 163,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Základy toxikologie',
    category: 'Nebezpečné látky',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'nebezpecne-latky-zaklady-toxikologie',
    sortOrder: 164,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Bojové chemické látky',
    category: 'Nebezpečné látky',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'nebezpecne-latky-bojove-chemicke-latky',
    sortOrder: 165,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Technická služba',
    category: 'Technická služba',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'technicka-sluzba-technicka-sluzba',
    sortOrder: 166,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Předpisy technické služby',
    category: 'Technická služba',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'technicka-sluzba-predpisy-technicke-sluzby',
    sortOrder: 167,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Prostředky technické služby',
    category: 'Technická služba',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'technicka-sluzba-prostredky-technicke-sluzby',
    sortOrder: 168,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Vzory označení hasičů',
    category: 'Technická služba',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'technicka-sluzba-vzory-oznaceni-hasicu',
    sortOrder: 169,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Požadavky na prostředky technické služby',
    category: 'Technická služba',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'technicka-sluzba-pozadavky-na-prostredky-technicke-sluzby',
    sortOrder: 170,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Práce pod vodní hladinou',
    category: 'Práce pod vodní hladinou',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'prace-pod-vodni-hladinou-prace-pod-vodni-hladinou',
    sortOrder: 171,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Posuzování požárního nebezpečí',
    category: 'Požární prevence',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'pozarni-prevence-posuzovani-pozarniho-nebezpeci',
    sortOrder: 172,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Členění provozovaných činností podle požárního nebezpečí',
    category: 'Požární prevence',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'pozarni-prevence-cleneni-provozovanych-cinnosti-podle-pozarniho-nebezpeci',
    sortOrder: 173,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Společné povinnosti právnických a podnikajících fyzických osob na úseku PO',
    category: 'Požární prevence',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'pozarni-prevence-spolecne-povinnosti-pravnickych-a-podnikajicich-fyzickych-osob-na-useku-po',
    sortOrder: 174,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Povinnosti PO a PFO při zvýšeném požárním nebezpečí',
    category: 'Požární prevence',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'pozarni-prevence-povinnosti-po-a-pfo-pri-zvysenem-pozarnim-nebezpeci',
    sortOrder: 175,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Povinnosti při vysokém požárním nebezpečí',
    category: 'Požární prevence',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'pozarni-prevence-povinnosti-pri-vysokem-pozarnim-nebezpeci',
    sortOrder: 176,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Podmínky požární bezpečnosti',
    category: 'Požární prevence',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'pozarni-prevence-podminky-pozarni-bezpecnosti',
    sortOrder: 177,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Dokumentace PO',
    category: 'Požární prevence',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'pozarni-prevence-dokumentace-po',
    sortOrder: 178,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Posouzení požárního nebezpečí',
    category: 'Požární prevence',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'pozarni-prevence-posouzeni-pozarniho-nebezpeci',
    sortOrder: 179,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Způsob posuzování požárního nebezpečí',
    category: 'Požární prevence',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'pozarni-prevence-zpusob-posuzovani-pozarniho-nebezpeci',
    sortOrder: 180,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Funkce PBZ',
    category: 'Požárně bezpečnostní zařízení',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'pozarne-bezpecnostni-zarizeni-funkce-pbz',
    sortOrder: 181,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Rozdělení PBZ',
    category: 'Požárně bezpečnostní zařízení',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'pozarne-bezpecnostni-zarizeni-rozdeleni-pbz',
    sortOrder: 182,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Definice PBZ',
    category: 'Požárně bezpečnostní zařízení',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'pozarne-bezpecnostni-zarizeni-definice-pbz',
    sortOrder: 183,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Legislativa PBZ',
    category: 'Požárně bezpečnostní zařízení',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'pozarne-bezpecnostni-zarizeni-legislativa-pbz',
    sortOrder: 184,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Obecné požadavky',
    category: 'Požárně bezpečnostní zařízení',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'pozarne-bezpecnostni-zarizeni-obecne-pozadavky',
    sortOrder: 185,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'EPS – úvod, funkce a předpisy',
    category: 'Požárně bezpečnostní zařízení',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'pozarne-bezpecnostni-zarizeni-eps-uvod-funkce-a-predpisy',
    sortOrder: 186,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'EPS – hlásiče požáru',
    category: 'Požárně bezpečnostní zařízení',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'pozarne-bezpecnostni-zarizeni-eps-hlasice-pozaru',
    sortOrder: 187,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Ústředna EPS',
    category: 'Požárně bezpečnostní zařízení',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'pozarne-bezpecnostni-zarizeni-ustredna-eps',
    sortOrder: 188,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Doplňující zařízení EPS',
    category: 'Požárně bezpečnostní zařízení',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'pozarne-bezpecnostni-zarizeni-doplnujici-zarizeni-eps',
    sortOrder: 189,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Stabilní hasicí zařízení',
    category: 'Požárně bezpečnostní zařízení',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'pozarne-bezpecnostni-zarizeni-stabilni-hasici-zarizeni',
    sortOrder: 190,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Další hasicí zařízení',
    category: 'Požárně bezpečnostní zařízení',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'pozarne-bezpecnostni-zarizeni-dalsi-hasici-zarizeni',
    sortOrder: 191,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Zařízení pro odvod kouře a tepla',
    category: 'Požárně bezpečnostní zařízení',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'pozarne-bezpecnostni-zarizeni-zarizeni-pro-odvod-koure-a-tepla',
    sortOrder: 192,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Další PBZ',
    category: 'Požárně bezpečnostní zařízení',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'pozarne-bezpecnostni-zarizeni-dalsi-pbz',
    sortOrder: 193,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Aplikace PBZ ve specifických prostorech',
    category: 'Požárně bezpečnostní zařízení',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'pozarne-bezpecnostni-zarizeni-aplikace-pbz-ve-specifickych-prostorech',
    sortOrder: 194,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Orientace ve stavební dokumentaci',
    category: 'Stavební dokumentace',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'stavebni-dokumentace-orientace-ve-stavebni-dokumentaci',
    sortOrder: 195,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Druhy stavebních výkresů',
    category: 'Stavební dokumentace',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'stavebni-dokumentace-druhy-stavebnich-vykresu',
    sortOrder: 196,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Formáty výkresů',
    category: 'Stavební dokumentace',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'stavebni-dokumentace-formaty-vykresu',
    sortOrder: 197,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Význam čar',
    category: 'Stavební dokumentace',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'stavebni-dokumentace-vyznam-car',
    sortOrder: 198,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Zásady kótování',
    category: 'Stavební dokumentace',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'stavebni-dokumentace-zasady-kotovani',
    sortOrder: 199,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Písmo na výkresu',
    category: 'Stavební dokumentace',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'stavebni-dokumentace-pismo-na-vykresu',
    sortOrder: 200,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Grafické a písemné značky',
    category: 'Stavební dokumentace',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'stavebni-dokumentace-graficke-a-pisemne-znacky',
    sortOrder: 201,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Označování stavebních hmot',
    category: 'Stavební dokumentace',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'stavebni-dokumentace-oznacovani-stavebnich-hmot',
    sortOrder: 202,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Svislé konstrukce',
    category: 'Stavební dokumentace',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'stavebni-dokumentace-svisle-konstrukce',
    sortOrder: 203,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Vodorovné konstrukce',
    category: 'Stavební dokumentace',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'stavebni-dokumentace-vodorovne-konstrukce',
    sortOrder: 204,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Schodiště',
    category: 'Stavební dokumentace',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'stavebni-dokumentace-schodiste',
    sortOrder: 205,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Komíny',
    category: 'Stavební dokumentace',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'stavebni-dokumentace-kominy',
    sortOrder: 206,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Střechy',
    category: 'Stavební dokumentace',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'stavebni-dokumentace-strechy',
    sortOrder: 207,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Výkresy požární bezpečnosti staveb',
    category: 'Stavební dokumentace',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'stavebni-dokumentace-vykresy-pozarni-bezpecnosti-staveb',
    sortOrder: 208,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Psychologická služba',
    category: 'Psychologická příprava',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'psychologicka-priprava-psychologicka-sluzba',
    sortOrder: 209,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Psychická zátěž hasiče',
    category: 'Psychologická příprava',
    sourceType: 'INTERNAL',
    code: 'psychologicka-priprava-psychicka-zatez-hasice',
    sortOrder: 210,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Komunikace s postiženými',
    category: 'Psychologická příprava',
    sourceType: 'INTERNAL',
    code: 'psychologicka-priprava-komunikace-s-postizenymi',
    sortOrder: 211,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Zvládání stresových situací',
    category: 'Psychologická příprava',
    sourceType: 'INTERNAL',
    code: 'psychologicka-priprava-zvladani-stresovych-situaci',
    sortOrder: 212,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Integrovaný záchranný systém',
    category: 'IZS',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'izs-integrovany-zachranny-system',
    sortOrder: 213,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Typové činnosti složek IZS',
    category: 'IZS',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'izs-typove-cinnosti-slozek-izs',
    sortOrder: 214,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Analýza vybraných zásahů JPO a IZS',
    category: 'IZS',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'izs-analyza-vybranych-zasahu-jpo-a-izs',
    sortOrder: 215,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Letečtí záchranáři',
    category: 'IZS',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'izs-letecti-zachranari',
    sortOrder: 216,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Letecká hasičská služba',
    category: 'IZS',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'izs-letecka-hasicska-sluzba',
    sortOrder: 217,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Spolupráce s PČR',
    category: 'IZS',
    sourceType: 'INTERNAL',
    code: 'izs-spoluprace-s-pcr',
    sortOrder: 218,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Spolupráce se ZZS',
    category: 'IZS',
    sourceType: 'INTERNAL',
    code: 'izs-spoluprace-se-zzs',
    sortOrder: 219,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Spolupráce s HZS ČR',
    category: 'IZS',
    sourceType: 'INTERNAL',
    code: 'izs-spoluprace-s-hzs-cr',
    sortOrder: 220,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Komunikace s KOPIS',
    category: 'IZS',
    sourceType: 'INTERNAL',
    code: 'izs-komunikace-s-kopis',
    sortOrder: 221,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Velitel zásahu',
    category: 'IZS',
    sourceType: 'INTERNAL',
    code: 'izs-velitel-zasahu',
    sortOrder: 222,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Řízení zásahu',
    category: 'IZS',
    sourceType: 'INTERNAL',
    code: 'izs-rizeni-zasahu',
    sortOrder: 223,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Materiály ke stažení a odborné přípravě',
    category: 'Odborná příprava JSDHO',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'odborna-priprava-jsdho-materialy-ke-stazeni-a-odborne-priprave',
    sortOrder: 224,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Základní pravidelná odborná příprava',
    category: 'Odborná příprava JSDHO',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'odborna-priprava-jsdho-zakladni-pravidelna-odborna-priprava',
    sortOrder: 225,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Podpora velitele dobrovolné jednotky v oblasti ZOP',
    category: 'Odborná příprava JSDHO',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'odborna-priprava-jsdho-podpora-velitele-dobrovolne-jednotky-v-oblasti-zop',
    sortOrder: 226,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Vyhodnocení odborné přípravy',
    category: 'Odborná příprava JSDHO',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'odborna-priprava-jsdho-vyhodnoceni-odborne-pripravy',
    sortOrder: 227,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Odborná způsobilost členů – osnovy kurzů',
    category: 'Odborná způsobilost',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'odborna-zpusobilost-odborna-zpusobilost-clenu-osnovy-kurzu',
    sortOrder: 228,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'V-40',
    category: 'Odborná způsobilost',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'odborna-zpusobilost-v-40',
    sortOrder: 229,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'V-8',
    category: 'Odborná způsobilost',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'odborna-zpusobilost-v-8',
    sortOrder: 230,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'S-40',
    category: 'Odborná způsobilost',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'odborna-zpusobilost-s-40',
    sortOrder: 231,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'S-16',
    category: 'Odborná způsobilost',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'odborna-zpusobilost-s-16',
    sortOrder: 232,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'S-8',
    category: 'Odborná způsobilost',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'odborna-zpusobilost-s-8',
    sortOrder: 233,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Technik ochrany obyvatelstva',
    category: 'Specializační kurzy',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'specializacni-kurzy-technik-ochrany-obyvatelstva',
    sortOrder: 234,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'NDT-16',
    category: 'Specializační kurzy',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'specializacni-kurzy-ndt-16',
    sortOrder: 235,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Základy zdravotnických znalostí',
    category: 'Specializační kurzy',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'specializacni-kurzy-zaklady-zdravotnickych-znalosti',
    sortOrder: 236,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Práce na vodě',
    category: 'Specializační kurzy',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'specializacni-kurzy-prace-na-vode',
    sortOrder: 237,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Obsluha MP v jednotce PO',
    category: 'Specializační kurzy',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'specializacni-kurzy-obsluha-mp-v-jednotce-po',
    sortOrder: 238,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Vyprošťování osob z vozidel – SDH',
    category: 'Specializační kurzy',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'specializacni-kurzy-vyprostovani-osob-z-vozidel-sdh',
    sortOrder: 239,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Technik dobrovolné jednotky PO – TCH-16',
    category: 'Specializační kurzy',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'specializacni-kurzy-technik-dobrovolne-jednotky-po-tch-16',
    sortOrder: 240,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Technik strojní služby – T-STS JSDHO',
    category: 'Specializační kurzy',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'specializacni-kurzy-technik-strojni-sluzby-t-sts-jsdho',
    sortOrder: 241,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Ochrana obyvatelstva u jednotek SDH obcí',
    category: 'Ochrana obyvatelstva',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'ochrana-obyvatelstva-ochrana-obyvatelstva-u-jednotek-sdh-obci',
    sortOrder: 242,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Technik ochrany obyvatelstva',
    category: 'Ochrana obyvatelstva',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'ochrana-obyvatelstva-technik-ochrany-obyvatelstva',
    sortOrder: 243,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Evakuace',
    category: 'Ochrana obyvatelstva',
    sourceType: 'INTERNAL',
    code: 'ochrana-obyvatelstva-evakuace',
    sortOrder: 244,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Nouzové přežití',
    category: 'Ochrana obyvatelstva',
    sourceType: 'INTERNAL',
    code: 'ochrana-obyvatelstva-nouzove-preziti',
    sortOrder: 245,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Varování obyvatelstva',
    category: 'Ochrana obyvatelstva',
    sourceType: 'INTERNAL',
    code: 'ochrana-obyvatelstva-varovani-obyvatelstva',
    sortOrder: 246,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Ukrytí obyvatelstva',
    category: 'Ochrana obyvatelstva',
    sourceType: 'INTERNAL',
    code: 'ochrana-obyvatelstva-ukryti-obyvatelstva',
    sortOrder: 247,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Humanitární pomoc',
    category: 'Ochrana obyvatelstva',
    sourceType: 'INTERNAL',
    code: 'ochrana-obyvatelstva-humanitarni-pomoc',
    sortOrder: 248,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Dokumentace jednotky',
    category: 'Dokumentace jednotky',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dokumentace-jednotky-dokumentace-jednotky',
    sortOrder: 249,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'ZOZ',
    category: 'Dokumentace jednotky',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dokumentace-jednotky-zoz',
    sortOrder: 250,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Metodiky',
    category: 'Dokumentace jednotky',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dokumentace-jednotky-metodiky',
    sortOrder: 251,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Řády',
    category: 'Dokumentace jednotky',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dokumentace-jednotky-rady',
    sortOrder: 252,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Dokumentace odborné přípravy',
    category: 'Dokumentace jednotky',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dokumentace-jednotky-dokumentace-odborne-pripravy',
    sortOrder: 253,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Evidence odborné přípravy',
    category: 'Dokumentace jednotky',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'dokumentace-jednotky-evidence-odborne-pripravy',
    sortOrder: 254,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Karta KID',
    category: 'Specifické situace',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'specificke-situace-karta-kid',
    sortOrder: 255,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Problematika kriminality dětí',
    category: 'Specifické situace',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'specificke-situace-problematika-kriminality-deti',
    sortOrder: 256,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Problematika kriminality páchané na dětech',
    category: 'Specifické situace',
    sourceType: 'HASICI_VZDELAVANI',
    code: 'specificke-situace-problematika-kriminality-pachane-na-detech',
    sortOrder: 257,
    source: 'HasičiVzdělávání – Vzdělávací portál jednotek PO',
    sourceUrl:
      'https://www.hasici-vzdelavani.cz/content/souhrn-metodickych-predpisu',
  },
  {
    name: 'Organizace jednotky PO',
    category: 'Organizace jednotky',
    sourceType: 'INTERNAL',
    code: 'organizace-jednotky-organizace-jednotky-po',
    sortOrder: 258,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Povinnosti člena jednotky',
    category: 'Organizace jednotky',
    sourceType: 'INTERNAL',
    code: 'organizace-jednotky-povinnosti-clena-jednotky',
    sortOrder: 259,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Povinnosti velitele',
    category: 'Organizace jednotky',
    sourceType: 'INTERNAL',
    code: 'organizace-jednotky-povinnosti-velitele',
    sortOrder: 260,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Povinnosti strojníka',
    category: 'Organizace jednotky',
    sourceType: 'INTERNAL',
    code: 'organizace-jednotky-povinnosti-strojnika',
    sortOrder: 261,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Povinnosti hasiče',
    category: 'Organizace jednotky',
    sourceType: 'INTERNAL',
    code: 'organizace-jednotky-povinnosti-hasice',
    sortOrder: 262,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Bezpečnost práce',
    category: 'Organizace jednotky',
    sourceType: 'INTERNAL',
    code: 'organizace-jednotky-bezpecnost-prace',
    sortOrder: 263,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Používání OOPP',
    category: 'Organizace jednotky',
    sourceType: 'INTERNAL',
    code: 'organizace-jednotky-pouzivani-oopp',
    sortOrder: 264,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Výjezd jednotky',
    category: 'Organizace jednotky',
    sourceType: 'INTERNAL',
    code: 'organizace-jednotky-vyjezd-jednotky',
    sortOrder: 265,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Příjezd k zásahu',
    category: 'Organizace jednotky',
    sourceType: 'INTERNAL',
    code: 'organizace-jednotky-prijezd-k-zasahu',
    sortOrder: 266,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Organizace místa zásahu',
    category: 'Organizace jednotky',
    sourceType: 'INTERNAL',
    code: 'organizace-jednotky-organizace-mista-zasahu',
    sortOrder: 267,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Taktické řízení',
    category: 'Organizace jednotky',
    sourceType: 'INTERNAL',
    code: 'organizace-jednotky-takticke-rizeni',
    sortOrder: 268,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Operační řízení',
    category: 'Organizace jednotky',
    sourceType: 'INTERNAL',
    code: 'organizace-jednotky-operacni-rizeni',
    sortOrder: 269,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Spojení a radioprovoz',
    category: 'Organizace jednotky',
    sourceType: 'INTERNAL',
    code: 'organizace-jednotky-spojeni-a-radioprovoz',
    sortOrder: 270,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'KOPIS',
    category: 'Organizace jednotky',
    sourceType: 'INTERNAL',
    code: 'organizace-jednotky-kopis',
    sortOrder: 271,
    source: null,
    sourceUrl: null,
  },
  {
    name: 'Dokumentace zásahu',
    category: 'Organizace jednotky',
    sourceType: 'INTERNAL',
    code: 'organizace-jednotky-dokumentace-zasahu',
    sortOrder: 272,
    source: null,
    sourceUrl: null,
  },
] as const;

export async function importTrainingTopics(
  upsert: (topic: (typeof trainingTopicCatalog)[number]) => Promise<unknown>,
) {
  for (const topic of trainingTopicCatalog) await upsert(topic);
}
