'use client';

import { useState } from 'react';
import { History, Pencil, Plus, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { czechMonthLabel, driverDuty, dtDuty, formatActivityDate, latestDriverActivity, type ActivityType, type ConditioningData, type DriverActivityRow, type DtActivityRow } from '@/lib/conditioning';

type FormState={kind:'dt'|'driver';id:string|null;memberId:string;type:ActivityType;date:string;cylinderNumber:string;carrierNumber:string;maskNumber:string;vehicle:string;kilometers:string;incidentReference:string;note:string};
const typeLabel=(kind:'dt'|'driver',type:ActivityType)=>type==='INCIDENT'?(kind==='dt'?'Použití při zásahu':'Jízda k zásahu'):(kind==='dt'?'Kondiční prodýchávání':'Kondiční jízda');
const todayValue=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Prague',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());

export function ConditioningModule({data,onChange,notify}:{data:ConditioningData;onChange:(data:ConditioningData)=>void;notify:(message:string)=>void}){
  const [form,setForm]=useState<FormState|null>(null),[history,setHistory]=useState<{kind:'dt'|'driver';memberId:string}|null>(null),[saving,setSaving]=useState(false);
  const now=new Date(),dtMembers=data.members.filter(member=>member.dt),drivers=data.members.filter(member=>member.canDrive),month=czechMonthLabel(now);
  const openForm=(kind:'dt'|'driver',memberId:string,type:ActivityType,activity?:DtActivityRow|DriverActivityRow)=>setForm({kind,id:activity?.id??null,memberId,type:activity?.type??type,date:activity?.date??todayValue(),cylinderNumber:activity&&'cylinderNumber'in activity?activity.cylinderNumber:'',carrierNumber:activity&&'carrierNumber'in activity?activity.carrierNumber:'',maskNumber:activity&&'maskNumber'in activity?activity.maskNumber:'',vehicle:activity&&'vehicle'in activity?activity.vehicle:'',kilometers:activity&&'kilometers'in activity&&activity.kilometers!==null?String(activity.kilometers):'',incidentReference:activity?.incidentReference??'',note:activity?.note??''});
  const save=async()=>{if(!form)return;setSaving(true);try{const endpoint=`/api/conditioning/${form.kind}${form.id?`/${form.id}`:''}`,payload=form.kind==='dt'?{memberId:form.memberId,date:form.date,type:form.type,cylinderNumber:form.cylinderNumber,carrierNumber:form.carrierNumber,maskNumber:form.maskNumber,incidentReference:form.incidentReference,note:form.note}:{memberId:form.memberId,date:form.date,type:form.type,vehicle:form.vehicle,kilometers:form.kilometers===''?null:Number(form.kilometers),incidentReference:form.incidentReference,note:form.note};const response=await fetch(endpoint,{method:form.id?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}),body=await response.json();if(!response.ok)throw new Error(body.error);if(form.kind==='dt'){const activity=body.activity as DtActivityRow;onChange({...data,dtActivities:form.id?data.dtActivities.map(item=>item.id===activity.id?activity:item):[...data.dtActivities,activity]});}else{const activity=body.activity as DriverActivityRow;onChange({...data,driverActivities:form.id?data.driverActivities.map(item=>item.id===activity.id?activity:item):[...data.driverActivities,activity]});}setForm(null);notify('Záznam byl uložen.');}catch(error){notify(error instanceof Error?error.message:'Záznam se nepodařilo uložit.')}finally{setSaving(false)}};
  const remove=async(kind:'dt'|'driver',id:string)=>{if(!window.confirm('Opravdu chcete tento záznam odstranit?'))return;const response=await fetch(`/api/conditioning/${kind}/${id}`,{method:'DELETE'});if(!response.ok){const body=await response.json().catch(()=>({}));notify(body.error??'Záznam se nepodařilo odstranit.');return}onChange(kind==='dt'?{...data,dtActivities:data.dtActivities.filter(item=>item.id!==id)}:{...data,driverActivities:data.driverActivities.filter(item=>item.id!==id)});notify('Záznam byl odstraněn.');};
  const historyMember=data.members.find(member=>member.id===history?.memberId),historyRows=history?.kind==='dt'?data.dtActivities.filter(item=>item.memberId===history.memberId).sort((a,b)=>b.date.localeCompare(a.date)):data.driverActivities.filter(item=>item.memberId===history?.memberId).sort((a,b)=>b.date.localeCompare(a.date));
  return <div className="module-stack"><div className="module-title"><div><span className="section-kicker">Evidence pravidelných povinností</span><h2>Kondice a povinnosti</h2></div></div>
    <article className="panel table-panel"><div className="panel-table-title"><div><h2>Dýchací technika</h2><span>Aktivní nositelé DT · další termín přesně za 3 kalendářní měsíce</span></div><Badge variant="outline">{dtMembers.length} členů</Badge></div><div className="responsive-table"><table><thead><tr><th>Člen</th><th>Poslední DT</th><th>Typ</th><th>Další termín</th><th>Zbývá</th><th>Stav</th><th>Akce</th></tr></thead><tbody>{dtMembers.map(member=>{const duty=dtDuty(member,data.dtActivities,now,data.warningDays)!,last=duty.last;return <tr key={member.id}><td><strong>{member.name}</strong></td><td>{last?formatActivityDate(new Date(`${last.date}T12:00:00Z`)):'—'}</td><td>{last?typeLabel('dt',last.type):'—'}</td><td>{duty.due?formatActivityDate(new Date(`${duty.due}T12:00:00Z`)):'—'}</td><td>{duty.days===null?'Bez záznamu':duty.days<0?`${Math.abs(duty.days)} dní po termínu`:`${duty.days} dní`}</td><td><span className={`health-status ${duty.status==='ok'?'valid':duty.status}`}>{duty.status==='ok'?'V pořádku':duty.status==='warning'?'Do 30 dní':duty.status==='expired'?'Po termínu':'Bez záznamu'}</span></td><td><span className="conditioning-actions"><Button size="sm" variant="outline" onClick={()=>openForm('dt',member.id,'CONDITIONING')}><Plus/>Prodýchávání</Button><Button size="sm" variant="outline" onClick={()=>openForm('dt',member.id,'INCIDENT')}><Plus/>Použití při zásahu</Button><Button size="icon-sm" variant="ghost" aria-label={`Historie DT ${member.name}`} onClick={()=>setHistory({kind:'dt',memberId:member.id})}><History/></Button></span></td></tr>})}</tbody></table></div></article>
    <article className="panel table-panel"><div className="panel-table-title"><div><h2>Kondiční jízdy</h2><span>{month} · sledují se všichni členové s oprávněním strojníka</span></div><Badge variant="outline">{drivers.length} strojníků</Badge></div><div className="responsive-table"><table><thead><tr><th>Strojník</th><th>Tento měsíc</th><th>Poslední jízda</th><th>Typ</th><th>Vozidlo</th><th>KM</th><th>Stav</th><th>Akce</th></tr></thead><tbody>{drivers.map(member=>{const duty=driverDuty(member,data.driverActivities,now)!,last=latestDriverActivity(member.id,data.driverActivities);return <tr key={member.id}><td><strong>{member.name}</strong></td><td>{duty.fulfilled?`${month} – splněno`:`${month} – chybí kondiční jízda`}</td><td>{last?formatActivityDate(new Date(`${last.date}T12:00:00Z`)):'—'}</td><td>{last?typeLabel('driver',last.type):'—'}</td><td>{last?.vehicle??'—'}</td><td>{last?.kilometers!==null&&last?.kilometers!==undefined?last.kilometers:'—'}</td><td><span className={`health-status ${duty.fulfilled?'valid':'warning'}`}>{duty.fulfilled?'Splněno':'Chybí'}</span></td><td><span className="conditioning-actions"><Button size="sm" variant="outline" onClick={()=>openForm('driver',member.id,'CONDITIONING')}><Plus/>Kondiční jízda</Button><Button size="sm" variant="outline" onClick={()=>openForm('driver',member.id,'INCIDENT')}><Plus/>Jízda k zásahu</Button><Button size="icon-sm" variant="ghost" aria-label={`Historie jízd ${member.name}`} onClick={()=>setHistory({kind:'driver',memberId:member.id})}><History/></Button></span></td></tr>})}</tbody></table></div></article>
    <Dialog open={!!form} onOpenChange={open=>{if(!open&&!saving)setForm(null)}}><DialogContent className="conditioning-dialog sm:!max-w-lg"><DialogHeader><DialogTitle>{form?.id?'Upravit záznam':form?typeLabel(form.kind,form.type):'Nový záznam'}</DialogTitle><DialogDescription>Záznam se uloží do historie člena a přepočítá jeho aktuální povinnost.</DialogDescription></DialogHeader>{form&&<div className="conditioning-form"><label>Člen<select value={form.memberId} onChange={event=>setForm({...form,memberId:event.target.value})}>{data.members.filter(member=>form.kind==='dt'?member.dt:member.canDrive).map(member=><option key={member.id} value={member.id}>{member.name}</option>)}</select></label><label>Typ<select value={form.type} onChange={event=>setForm({...form,type:event.target.value as ActivityType})}><option value="CONDITIONING">{form.kind==='dt'?'Kondiční prodýchávání':'Kondiční jízda'}</option><option value="INCIDENT">{form.kind==='dt'?'Použití DT při zásahu':'Jízda k zásahu'}</option></select></label><label>Datum<input type="date" value={form.date} onChange={event=>setForm({...form,date:event.target.value})}/></label>{form.kind==='dt'?<div className="conditioning-grid"><label>Láhev<input value={form.cylinderNumber} onChange={event=>setForm({...form,cylinderNumber:event.target.value})}/></label><label>Nosič<input value={form.carrierNumber} onChange={event=>setForm({...form,carrierNumber:event.target.value})}/></label><label>Maska<input value={form.maskNumber} onChange={event=>setForm({...form,maskNumber:event.target.value})}/></label></div>:<div className="conditioning-grid"><label>Vozidlo<input required value={form.vehicle} onChange={event=>setForm({...form,vehicle:event.target.value})} placeholder="CAS TATRA"/></label><label>Počet km<input type="number" min="0" value={form.kilometers} onChange={event=>setForm({...form,kilometers:event.target.value})}/></label></div>}<label>Číslo / označení zásahu<input value={form.incidentReference} onChange={event=>setForm({...form,incidentReference:event.target.value})}/></label><label>Poznámka<textarea value={form.note} onChange={event=>setForm({...form,note:event.target.value})}/></label></div>}<DialogFooter><Button variant="outline" onClick={()=>setForm(null)} disabled={saving}>Zrušit</Button><Button className="primary-action compact" onClick={()=>void save()} disabled={saving}>{saving?'Ukládám…':'Uložit záznam'}</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={!!history} onOpenChange={open=>{if(!open)setHistory(null)}}><DialogContent className="conditioning-history-dialog sm:!max-w-3xl"><DialogHeader><DialogTitle>Historie – {historyMember?.name}</DialogTitle><DialogDescription>{history?.kind==='dt'?'Dýchací technika':'Kondiční jízdy a jízdy k zásahu'}</DialogDescription></DialogHeader><div className="responsive-table conditioning-history"><table><thead><tr><th>Datum</th><th>Typ</th><th>Podrobnosti</th><th>Zásah</th><th>Poznámka</th><th>Akce</th></tr></thead><tbody>{historyRows.length?historyRows.map(activity=><tr key={activity.id}><td>{formatActivityDate(new Date(`${activity.date}T12:00:00Z`))}</td><td>{typeLabel(history!.kind,activity.type)}</td><td>{'vehicle'in activity?`${activity.vehicle}${activity.kilometers!==null?` · ${activity.kilometers} km`:''}`:[activity.cylinderNumber&&`Láhev ${activity.cylinderNumber}`,activity.carrierNumber&&`Nosič ${activity.carrierNumber}`,activity.maskNumber&&`Maska ${activity.maskNumber}`].filter(Boolean).join(' · ')||'—'}</td><td>{activity.incidentReference||'—'}</td><td>{activity.note||'—'}</td><td><span className="record-actions"><Button variant="ghost" size="icon-sm" onClick={()=>{openForm(history!.kind,activity.memberId,activity.type,activity);setHistory(null)}} aria-label="Upravit"><Pencil/></Button><Button variant="ghost" size="icon-sm" className="delete-action" onClick={()=>void remove(history!.kind,activity.id)} aria-label="Odstranit"><Trash2/></Button></span></td></tr>):<tr><td colSpan={6}>Zatím bez záznamu.</td></tr>}</tbody></table></div></DialogContent></Dialog>
  </div>;
}
