'use client';

import { useMemo, useState } from 'react';
import { Activity, AlertTriangle, Check, ChevronRight, ClipboardList, Download, FileText, Gauge, HeartPulse, History, LayoutDashboard, Menu, Pencil, Settings, ShieldCheck, Siren, Stethoscope, Trash2, Upload, Users } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle } from '@/components/ui/sheet';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from '@/components/ui/alert-dialog';
import { buildWhatsAppMessage, createWhatsAppShareUrl } from '@/lib/whatsapp';
import type { AbsenceRow, MemberRow } from '@/lib/member-data';
import { MemberImportDialog } from '@/app/member-import-dialog';
import { DEFAULT_SERVICE_SETTINGS, formatServiceDateTime, fromLocalDateTimeInput, nextServiceWeek, serviceWeek, toLocalDateTimeInput, wholeDay, type ServiceTimeSettings } from '@/lib/service';

const nav = [[LayoutDashboard, 'Přehled'], [Siren, 'Týdenní služba'], [AlertTriangle, 'Nedostupnost'], [Users, 'Členové'], [Stethoscope, 'Zdravotní prohlídky'], [History, 'Historie'], [Activity, 'Statistiky'], [ClipboardList, 'Audit'], [Settings, 'Nastavení']] as const;
export type DashboardService={id:string;from:string;to:string;crew:{role:'Velitel'|'Strojník'|'Hasič';name:string;tag:string;dt:boolean}[]};

export function ServiceApp({ adminName = 'Administrátor', initialMembers, initialAbsences, initialTemplateName, initialSettings = DEFAULT_SERVICE_SETTINGS, initialCurrentService = null }: { adminName?: string; initialMembers: MemberRow[]; initialAbsences: AbsenceRow[]; initialTemplateName: string | null; initialSettings?: ServiceTimeSettings; initialCurrentService?:DashboardService|null }) {
  const [active, setActive] = useState('Přehled');
  const [menuOpen, setMenuOpen] = useState(false);
  const [notice, setNotice] = useState<string | null>(null);
  const today = useMemo(() => new Intl.DateTimeFormat('cs-CZ', { weekday: 'long', day: 'numeric', month: 'long' }).format(new Date()), []);
  const act = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(null), 2600); };
  const shareCurrentService=()=>{if(!initialCurrentService){act('Aktuální potvrzená posádka zatím není k dispozici.');return}const commander=initialCurrentService.crew.find(member=>member.role==='Velitel'),driver=initialCurrentService.crew.find(member=>member.role==='Strojník'),firefighters=initialCurrentService.crew.filter(member=>member.role==='Hasič');if(!commander||!driver||firefighters.length!==2){act('Potvrzená posádka není kompletní.');return}const message=buildWhatsAppMessage({from:formatServiceDateTime(new Date(initialCurrentService.from),initialSettings.timezone),to:formatServiceDateTime(new Date(initialCurrentService.to),initialSettings.timezone),commander:commander.name,driver:driver.name,firefighters:[firefighters[0].name,firefighters[1].name],dt:initialCurrentService.crew.filter(member=>member.dt).map(member=>member.name)});window.open(createWhatsAppShareUrl(message),'_blank','noopener,noreferrer')};
  const metrics = [{ label: 'Aktivní členové', value: String(initialMembers.length), note: 'v evidenci', Icon: Users, tone: 'neutral' }, { label: 'Dostupní tento týden', value: String(Math.max(0, initialMembers.length - initialAbsences.length)), note: 'orientační stav', Icon: ShieldCheck, tone: 'ok' }, { label: 'Nositelé DT', value: String(initialMembers.filter((member) => member[4] === 'Ano').length), note: 'aktivních členů', Icon: Gauge, tone: 'neutral' }, { label: 'Zdravotní končí', value: '—', note: 'viz zdravotní prohlídky', Icon: HeartPulse, tone: 'warn' }];
  const nextWeek=nextServiceWeek(new Date(),initialSettings);

  return <div className="min-h-screen bg-background text-foreground">
    <aside className={`sidebar-shell ${menuOpen ? 'sidebar-open' : ''}`}>
      <div className="brand-block"><div className="brand-mark"><Siren size={22} /></div><div><strong>JSDH NEHVIZDY</strong><span>Týdenní služba</span></div></div>
      <nav className="nav-list" aria-label="Hlavní navigace">{nav.map(([Icon, label]) => <button key={label} className={active === label ? 'active' : ''} onClick={() => { setActive(label); setMenuOpen(false); }}><Icon size={19} strokeWidth={1.8} /><span>{label}</span></button>)}</nav>
      <form action="/api/auth/logout" method="post"><button className="admin-card" type="submit" title="Odhlásit se"><span className="admin-avatar">{adminName.split(' ').map(part => part[0]).join('').slice(0,2).toUpperCase()}</span><span><strong>{adminName}</strong><small>Odhlásit se</small></span><ChevronRight size={16} /></button></form>
    </aside>
    <main className="main-shell">
      <header className="topbar"><button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-label="Otevřít menu"><Menu /></button><div><span className="eyebrow">{today}</span><h1>{active}</h1></div><div className="system-status"><span /><div><strong>Systém připraven</strong><small>Europe/Prague</small></div></div></header>
      <section className="content-shell">
        {active === 'Přehled' ? <>
        <div className="metric-grid">{metrics.map(({ label, value, note, Icon, tone }) => <article className="metric-card" key={label}><div className={`metric-icon ${tone}`}><Icon size={20} /></div><div><p>{label}</p><strong>{value}</strong><span>{note}</span></div></article>)}</div>
        <div className="dashboard-grid">
          <article className="service-card">
            <div className="card-heading"><div><span className="section-kicker">Aktuální služba</span><h2>{initialCurrentService?`${formatServiceDateTime(new Date(initialCurrentService.from),initialSettings.timezone)} → ${formatServiceDateTime(new Date(initialCurrentService.to),initialSettings.timezone)}`:'Žádná potvrzená služba'}</h2><p>{initialCurrentService?'Sestava načtená z evidence':'Pro aktuální interval není uložená potvrzená posádka.'}</p></div>{initialCurrentService&&<Badge className="status-badge"><Check size={13} /> Potvrzena</Badge>}</div>
            {initialCurrentService?<><div className="crew-list">{initialCurrentService.crew.map((member, index) => <div className="crew-row" key={`${member.role}-${member.name}-${index}`}><span className={`role-index ${index === 0 ? 'lead' : ''}`}>{index + 1}</span><div className="crew-copy"><span>{member.role}</span><strong>{member.name}</strong></div><span className="role-tag">{member.tag}</span>{member.dt && <span className="dt-tag"><Gauge size={14} /> DT</span>}</div>)}</div><div className="service-footer"><div><ShieldCheck size={18} /><span><strong>Potvrzená posádka</strong><small>Údaje pocházejí z PostgreSQL</small></span></div><Button variant="outline" onClick={() => setActive('Týdenní služba')}>Zobrazit detail</Button></div></>:<div className="empty-absence dashboard-empty"><Siren/><strong>Posádka zatím není připravena</strong><span>Vytvořte a potvrďte službu z vlastních členů jednotky.</span></div>}
          </article>
          <aside className="next-card"><div className="next-head"><span className="section-kicker">Příští týden</span><Badge variant="outline">{formatServiceDateTime(nextWeek.start,initialSettings.timezone)}</Badge></div><h2>Kontrola dostupnosti</h2><div className="availability-score"><strong>{initialMembers.length}</strong><span>aktivních<br />členů</span></div><div className="capacity-list"><div><span>Velitelé</span><strong>{initialMembers.filter(member=>member[3].includes('Velitel')).length}</strong></div><div><span>Strojníci</span><strong>{initialMembers.filter(member=>member[3].includes('Strojník')).length}</strong></div><div><span>Nositelé DT</span><strong>{initialMembers.filter(member=>member[4]==='Ano').length}</strong></div></div><div className="ready-state"><Check size={17} /><span><strong>Evidence připravena</strong><small>Pro návrh se použijí pouze vaši aktivní členové.</small></span></div><Button className="primary-action" onClick={() => setActive('Týdenní služba')}><Siren size={18} /> Připravit službu</Button></aside>
        </div>
        <section className="quick-section"><div><span className="section-kicker">Rychlé akce</span><h2>Co potřebujete udělat?</h2></div><div className="quick-grid"><button onClick={() => { setActive('Nedostupnost'); act('Vyberte člena a termín nedostupnosti.'); }}><span className="quick-icon red"><AlertTriangle /></span><span><strong>Přidat nedostupnost</strong><small>Člen nebude zahrnut do losování</small></span><ChevronRight /></button><button onClick={() => setActive('Týdenní služba')}><span className="quick-icon"><Siren /></span><span><strong>Připravit příští službu</strong><small>Kontrola a chytré losování 3+1</small></span><ChevronRight /></button><button onClick={shareCurrentService}><span className="quick-icon"><ClipboardList /></span><span><strong>Sdílet službu</strong><small>Otevřít potvrzenou posádku ve WhatsApp</small></span><ChevronRight /></button></div></section>
        </> : <ModuleView active={active} notify={act} initialMembers={initialMembers} initialAbsences={initialAbsences} initialTemplateName={initialTemplateName} initialSettings={initialSettings} currentService={initialCurrentService} onShareCurrentService={shareCurrentService} />}
      </section>
    </main>
    {menuOpen && <button className="backdrop" onClick={() => setMenuOpen(false)} aria-label="Zavřít menu" />}
    {notice && <div className="toast-notice"><Check size={18} />{notice}</div>}
  </div>;
}

function ModuleView({ active, notify, initialMembers, initialAbsences, initialTemplateName, initialSettings, currentService, onShareCurrentService }: { active:string; notify:(message:string)=>void; initialMembers:MemberRow[]; initialAbsences:AbsenceRow[]; initialTemplateName:string|null; initialSettings:ServiceTimeSettings; currentService:DashboardService|null; onShareCurrentService:()=>void }) {
  const [memberRows, setMemberRows] = useState<MemberRow[]>(()=>initialMembers.map(member=>[...member] as MemberRow));
  const [selectedMember, setSelectedMember] = useState<MemberRow | null>(null);
  const [editingMember, setEditingMember] = useState(false);
  const [memberImportOpen, setMemberImportOpen] = useState(false);
  const saveMember=async(updated:MemberRow)=>{try{const creating=!updated[5];const response=await fetch(creating?'/api/members':`/api/members/${updated[5]}`,{method:creating?'POST':'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({name:updated[0],role:updated[1],medicalValidUntil:updated[2],permissions:updated[3]?updated[3].split(' · '):[],dt:updated[4]==='Ano'})});const body=await response.json();if(!response.ok)throw new Error(body.error);const saved=body.member as MemberRow;setMemberRows(rows=>creating?[...rows,saved]:rows.map(row=>row[5]===saved[5]?saved:row));setSelectedMember(saved);notify(`Změny člena ${saved[0]} byly uloženy.`)}catch(error){notify(error instanceof Error?error.message:'Změny se nepodařilo uložit.');throw error}};
  const deleteMember=async(member:MemberRow)=>{const response=await fetch(`/api/members/${member[5]}`,{method:'DELETE'});if(!response.ok){notify('Člena se nepodařilo deaktivovat.');return}setMemberRows(rows=>rows.filter(row=>row[5]!==member[5]));setSelectedMember(null);notify(`Člen ${member[0]} byl deaktivován.`)};
  if(active==='Týdenní služba') return <div className="module-stack"><ModuleTitle kicker="Plánování 3+1" title="Týdenní služba"/><div className="week-strip"><button>←</button><div><strong>{currentService?`${formatServiceDateTime(new Date(currentService.from),initialSettings.timezone)} → ${formatServiceDateTime(new Date(currentService.to),initialSettings.timezone)}`:'Aktuální období'}</strong><span>Pondělí 06:00 — neděle 06:00</span></div><button>→</button></div><article className="panel">{currentService?<><div className="panel-head"><div><span className="section-kicker">Potvrzená sestava</span><h2>Posádka 3+1</h2></div><Badge className="status-badge"><Check size={13}/> Potvrzena</Badge></div><div className="crew-list">{currentService.crew.map((member,index)=><div className="crew-row" key={`${member.role}-${member.name}-${index}`}><span className={`role-index ${index===0?'lead':''}`}>{index+1}</span><div className="crew-copy"><span>{member.role}</span><strong>{member.name}</strong></div>{member.dt&&<span className="dt-tag"><Gauge size={14}/> DT</span>}</div>)}</div><div className="validation-box"><Check size={18}/><div><strong>Posádka je potvrzena</strong><span>Načteno z evidence týdenních služeb</span></div></div><div className="actions"><Button variant="outline" onClick={onShareCurrentService}>Sdílet na WhatsApp</Button></div></>:<div className="empty-absence"><Siren/><strong>Žádná potvrzená posádka</strong><span>Ukázkoví členové byli odstraněni. Zobrazí se pouze služba uložená v PostgreSQL.</span></div>}</article></div>;
  if(active==='Nedostupnost') return <UnavailabilityModule title={active} notify={notify} memberOptions={memberRows} initialRecords={initialAbsences} settings={initialSettings}/>;
  if(active==='Zdravotní prohlídky') return <div className="module-stack"><HealthModule memberRows={memberRows} initialTemplateName={initialTemplateName} onSelect={member=>{setSelectedMember(member);setEditingMember(false)}} notify={notify}/><MemberDetail key={selectedMember?.[5]??'closed'} member={selectedMember} editing={editingMember} onEditing={setEditingMember} onSave={saveMember} onDelete={deleteMember} onClose={()=>setSelectedMember(null)} notify={notify}/></div>;
  if(active==='Členové') return <div className="module-stack"><ModuleTitle kicker="Evidence jednotky" title={active} secondaryAction="Import členů" onSecondaryAction={()=>setMemberImportOpen(true)} action="+ Nový člen" onAction={()=>{setSelectedMember(['','Hasič','Neuvedeno','Hasič','Ne','']);setEditingMember(true)}}/><article className="panel table-panel"><div className="filter-row"><input placeholder="Hledat člena…"/><select><option>Všechny funkce</option><option>Velitel</option><option>Strojník</option><option>Hasič</option></select></div><div className="responsive-table"><table><thead><tr><th>Člen</th><th>Hlavní funkce</th><th>Zdravotní platná do</th><th>Oprávnění</th><th>DT</th><th>Stav</th><th><span className="sr-only">Akce</span></th></tr></thead><tbody>{memberRows.map((m)=><tr key={m[5]}><td><button className="member-link" onClick={()=>{setSelectedMember(m);setEditingMember(false)}}>{m[0]}</button></td><td>{m[1]}</td><td>{m[2]}</td><td>{m[3]}</td><td>{m[4]}</td><td><span className="status-dot ok"/>Aktivní</td><td><Button variant="ghost" size="sm" onClick={()=>{setSelectedMember(m);setEditingMember(false)}}>Detail</Button></td></tr>)}</tbody></table></div></article><MemberDetail key={selectedMember?.[5]??(selectedMember?'new':'closed')} member={selectedMember} editing={editingMember} onEditing={setEditingMember} onSave={saveMember} onDelete={deleteMember} onClose={()=>setSelectedMember(null)} notify={notify}/><MemberImportDialog open={memberImportOpen} onOpenChange={setMemberImportOpen} onImported={setMemberRows} notify={notify}/></div>;
  if(active==='Historie'||active==='Statistiky') return <div className="module-stack"><ModuleTitle kicker="Spravedlivé rozdělení" title={active}/><article className="panel table-panel"><div className="filter-row"><select><option>Rok 2026</option></select><select><option>Všichni členové</option></select><select><option>Všechny pozice</option></select></div><div className="responsive-table"><table><thead><tr>{(active==='Historie'?['Týden','Velitel','Strojník','Hasič 1','Hasič 2','DT','Stav']:['Člen','Celkem služeb','Velitel','Strojník','Hasič','Poslední služba','DT']).map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{active==='Historie'?<tr><td colSpan={7}>Historie služeb se zobrazí po vytvoření první služby.</td></tr>:memberRows.slice(0,7).map((m)=><tr key={m[5]}><td><strong>{m[0]}</strong></td><td>0</td><td>0</td><td>0</td><td>0</td><td>—</td><td>{m[4]}</td></tr>)}</tbody></table></div></article></div>;
  if(active==='Audit') return <div className="module-stack"><ModuleTitle kicker="Dohledatelnost" title="Audit změn"/><article className="panel"><div className="empty-absence"><ClipboardList/><strong>Audit se ukládá do PostgreSQL</strong><span>Záznamy vznikají při změnách členů, nedostupností a dokumentů.</span></div></article></div>;
  return <div className="module-stack"><ModuleTitle kicker="Pravidla aplikace" title="Nastavení"/><div className="split-panels"><article className="panel settings-panel"><h2>Interval služby</h2><div className="setting-row"><span><strong>Začátek</strong><small>Pevná lokální hranice</small></span><b>Pondělí 06:00</b></div><div className="setting-row"><span><strong>Konec</strong><small>{initialSettings.timezone}</small></span><b>Neděle 06:00</b></div><div className="setting-row"><span><strong>Minimální počet DT</strong><small>Vyhodnocuje se pro celou posádku</small></span><input type="number" min="1" defaultValue={initialSettings.minimumDt}/></div></article><article className="panel settings-panel"><h2>Spravedlivé losování</h2>{['Zohlednit celkový počet služeb','Zohlednit konkrétní funkci','Preferovat členy, kteří minulý týden nesloužili','Povolit dva týdny za sebou, není-li jiná možnost'].map(x=><label className="check-row" key={x}><span>{x}</span><input type="checkbox" defaultChecked/></label>)}<Button className="primary-action" onClick={()=>notify('Nastavení bylo uloženo.')}>Uložit nastavení</Button></article></div></div>;
}

function ModuleTitle({kicker,title,action,onAction,secondaryAction,onSecondaryAction}:{kicker:string;title:string;action?:string;onAction?:()=>void;secondaryAction?:string;onSecondaryAction?:()=>void}){return <div className="module-title"><div><span className="section-kicker">{kicker}</span><h2>{title}</h2></div><div className="module-actions">{secondaryAction&&<Button variant="outline" onClick={onSecondaryAction}>{secondaryAction}</Button>}{action&&<Button className="primary-action compact" onClick={onAction}>{action}</Button>}</div></div>}

function HealthModule({memberRows,initialTemplateName,onSelect,notify}:{memberRows:MemberRow[];initialTemplateName:string|null;onSelect:(member:MemberRow)=>void;notify:(message:string)=>void}) {
  const [templateName,setTemplateName]=useState<string|null>(initialTemplateName);
  const [uploading,setUploading]=useState(false);
  const uploadTemplate=async(file:File)=>{setUploading(true);try{const data=new FormData();data.append('file',file,file.name);const response=await fetch('/api/templates/medical',{method:'POST',body:data});const body=await response.json().catch(()=>({error:'Server nedokázal zpracovat nahraný soubor.'}));if(!response.ok)throw new Error(body.error);setTemplateName(body.filename);notify(`Vzor ${body.filename} byl uložen do databáze.`)}catch(error){notify(error instanceof Error?error.message:'Dokument se nepodařilo nahrát. Zkuste to znovu.')}finally{setUploading(false)}};
  const removeTemplate=async()=>{try{const response=await fetch('/api/templates/medical',{method:'DELETE'});if(!response.ok)throw new Error('delete failed');setTemplateName(null);notify('Vzor lékařského posudku byl odstraněn.')}catch{notify('Vzor se nepodařilo odstranit.')}};
  const parseDate=(value:string)=>{if(value==='Neuvedeno')return null;const [d,m,y]=value.split('.').map(Number);return new Date(y,m-1,d)};
  const today=new Date();
  const health=memberRows.map(member=>{const date=parseDate(member[2]);const days=date?Math.ceil((date.getTime()-today.getTime())/86400000):Number.POSITIVE_INFINITY;return{member,days,status:date?(days<0?'expired':days<=60?'warning':'valid'):'missing'}}).sort((a,b)=>a.days-b.days);
  const expired=health.filter(item=>item.status==='expired').length,warning=health.filter(item=>item.status==='warning').length,valid=health.filter(item=>item.status==='valid').length;
  const missing=health.filter(item=>item.status==='missing').length;
  return <><ModuleTitle kicker="Zdravotní způsobilost" title="Zdravotní prohlídky"/><article className="medical-template-card"><span className="template-file-icon"><FileText/></span><div><span className="section-kicker">Vzor dokumentu</span><strong>Lékařský posudek</strong><small>{templateName?`Aktuální soubor: ${templateName}`:'Vzor zatím nebyl nahrán'}</small></div><span className="template-actions">{templateName&&<a className="template-download" href="/api/templates/medical" download><Download/>Stáhnout vzor</a>}<label className={`template-upload ${uploading?'disabled':''}`}><Upload/>{uploading?'Nahrávám…':'Nahrát nový vzor'}<input type="file" accept=".doc,.docx,.pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/pdf" disabled={uploading} onChange={event=>{const file=event.target.files?.[0];if(file)void uploadTemplate(file);event.target.value=''}}/></label>{templateName&&<button className="restore-template" onClick={()=>void removeTemplate()}>Odstranit vzor</button>}</span></article><div className="health-summary"><article><span className="health-icon valid"><Check/></span><div><strong>{valid}</strong><span>Platná zdravotní</span></div></article><article><span className="health-icon warning"><AlertTriangle/></span><div><strong>{warning}</strong><span>Končí do 60 dní</span></div></article><article><span className="health-icon expired"><HeartPulse/></span><div><strong>{expired}</strong><span>Po platnosti</span></div></article><article><span className="health-icon neutral"><ClipboardList/></span><div><strong>{missing}</strong><span>Bez údajů</span></div></article></div><article className="panel table-panel health-table"><div className="panel-table-title"><div><h2>Platnost prohlídek</h2><span>Seřazeno podle nejbližšího konce platnosti</span></div><select><option>Všichni členové</option><option>Končí do 60 dní</option><option>Po platnosti</option></select></div><div className="responsive-table"><table><thead><tr><th>Člen</th><th>Hlavní funkce</th><th>Platná do</th><th>Zbývá dní</th><th>Stav</th><th><span className="sr-only">Akce</span></th></tr></thead><tbody>{health.map(({member,days,status})=><tr key={member[5]}><td><button className="member-link" onClick={()=>onSelect(member)}>{member[0]}</button></td><td>{member[1]}</td><td className={status==='expired'?'bad-date':status==='warning'?'warn-date':''}>{member[2]}</td><td>{status==='missing'?'—':days<0?`${Math.abs(days)} dní po platnosti`:days}</td><td><span className={`health-status ${status}`}>{status==='valid'?'Platná':status==='warning'?'Končí brzy':status==='expired'?'Po platnosti':'Bez údaje'}</span></td><td><Button variant="ghost" size="sm" onClick={()=>onSelect(member)}>Upravit</Button></td></tr>)}</tbody></table></div></article></>;
}

function UnavailabilityModule({title,notify,memberOptions,initialRecords,settings}:{title:string;notify:(message:string)=>void;memberOptions:MemberRow[];initialRecords:AbsenceRow[];settings:ServiceTimeSettings}) {
  const [records,setRecords] = useState<AbsenceRow[]>(initialRecords);
  const [editingId,setEditingId] = useState<string|null>(null);
  const [pendingDelete,setPendingDelete] = useState<AbsenceRow|null>(null);
  const [memberId,setMemberId] = useState(memberOptions[0]?.[5] ?? '');
  const initialRange=()=>serviceWeek(new Date(),settings);
  const [from,setFrom] = useState(()=>toLocalDateTimeInput(initialRange().start,settings.timezone));
  const [to,setTo] = useState(()=>toLocalDateTimeInput(initialRange().end,settings.timezone));
  const [reason,setReason] = useState('');
  const [preset,setPreset] = useState<'day'|'current'|'next'|'custom'>('current');
  const applyRange=(range:{start:Date;end:Date},nextPreset:typeof preset)=>{setFrom(toLocalDateTimeInput(range.start,settings.timezone));setTo(toLocalDateTimeInput(range.end,settings.timezone));setPreset(nextPreset)};
  const reset=()=>{const range=serviceWeek(new Date(),settings);setEditingId(null);setMemberId(memberOptions[0]?.[5]??'');applyRange(range,'current');setReason('')};
  const edit=(item:AbsenceRow)=>{setEditingId(item.id);setMemberId(item.memberId);setFrom(toLocalDateTimeInput(new Date(item.from),settings.timezone));setTo(toLocalDateTimeInput(new Date(item.to),settings.timezone));setPreset('custom');setReason(item.reason);window.scrollTo({top:0,behavior:'smooth'})};
  const save=async()=>{const fromDate=fromLocalDateTimeInput(from,settings.timezone),toDate=fromLocalDateTimeInput(to,settings.timezone);if(!memberId){notify('Nejdříve vytvořte člena.');return}if(!fromDate||!toDate||fromDate>=toDate){notify('Konec nedostupnosti musí být později než začátek.');return}try{const response=await fetch(editingId?`/api/unavailability/${editingId}`:'/api/unavailability',{method:editingId?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify({memberId,from:fromDate.toISOString(),to:toDate.toISOString(),reason})});const body=await response.json();if(!response.ok)throw new Error(body.error);const saved=body.record as AbsenceRow;setRecords(items=>editingId?items.map(item=>item.id===editingId?saved:item):[...items,saved]);notify(`Nedostupnost člena ${saved.member} byla uložena.`);reset()}catch(error){notify(error instanceof Error?error.message:'Nedostupnost se nepodařilo uložit.')}};
  const remove=async()=>{if(!pendingDelete)return;const response=await fetch(`/api/unavailability/${pendingDelete.id}`,{method:'DELETE'});if(!response.ok){notify('Nedostupnost se nepodařilo odstranit.');return}setRecords(items=>items.filter(item=>item.id!==pendingDelete.id));notify(`Nedostupnost člena ${pendingDelete.member} byla odstraněna.`);setPendingDelete(null);if(editingId===pendingDelete.id)reset()};
  const format=(value:string)=>formatServiceDateTime(new Date(value),settings.timezone);
  return <div className="module-stack">
    <ModuleTitle kicker="Evidence výjimek" title={title} action="Přidat nedostupnost" onAction={reset}/>
    <div className="split-panels"><article className="panel form-panel"><div className="form-title-row"><h2>{editingId?'Upravit nedostupnost':'Rychlé přidání'}</h2>{editingId&&<Badge variant="outline">Editace</Badge>}</div><label>Člen<select value={memberId} onChange={e=>setMemberId(e.target.value)}>{memberOptions.map(m=><option key={m[5]} value={m[5]}>{m[0]}</option>)}</select></label><div className="choice-row timed-choices"><button type="button" className={preset==='day'?'selected':''} onClick={()=>applyRange(wholeDay(new Date(),settings.timezone),'day')}>Celý den</button><button type="button" className={preset==='current'?'selected':''} onClick={()=>applyRange(serviceWeek(new Date(),settings),'current')}>Tento týden</button><button type="button" className={preset==='next'?'selected':''} onClick={()=>applyRange(nextServiceWeek(new Date(),settings),'next')}>Příští týden</button><button type="button" className={preset==='custom'?'selected':''} onClick={()=>setPreset('custom')}>Vlastní termín</button></div><div className="date-grid"><label>Od<input type="datetime-local" value={from} onChange={e=>{setFrom(e.target.value);setPreset('custom')}}/></label><label>Do<input type="datetime-local" value={to} onChange={e=>{setTo(e.target.value);setPreset('custom')}}/></label></div><label>Důvod (nepovinný)<input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Např. dovolená"/></label><div className="form-actions">{editingId&&<Button variant="outline" onClick={reset}>Zrušit</Button>}<Button className="primary-action" onClick={()=>void save()}>{editingId?'Uložit změny':'Uložit nedostupnost'}</Button></div></article>
      <article className="panel"><div className="panel-head"><h2>Nahlášené nedostupnosti</h2><Badge variant="outline">{records.length} {records.length===1?'záznam':'záznamy'}</Badge></div>{records.length?<div className="absence-list">{records.map(item=><div key={item.id}><span className="avatar-dot">{item.member.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><span><strong>{item.member}</strong><small>{format(item.from)} → {format(item.to)}</small>{item.reason&&<small className="absence-reason">{item.reason}</small>}</span><Badge variant="outline">{item.label}</Badge><span className="record-actions"><Button variant="ghost" size="icon-sm" onClick={()=>edit(item)} aria-label={`Upravit nedostupnost člena ${item.member}`}><Pencil/></Button><Button variant="ghost" size="icon-sm" className="delete-action" onClick={()=>setPendingDelete(item)} aria-label={`Odstranit nedostupnost člena ${item.member}`}><Trash2/></Button></span></div>)}</div>:<div className="empty-absence"><Check/><strong>Žádná nedostupnost</strong><span>Všichni aktivní členové jsou považováni za dostupné.</span></div>}</article></div>
    <AlertDialog open={!!pendingDelete} onOpenChange={open=>{if(!open)setPendingDelete(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Odstranit nedostupnost?</AlertDialogTitle><AlertDialogDescription>Záznam člena {pendingDelete?.member} bude odstraněn. Člen se může znovu účastnit losování, pokud splňuje ostatní podmínky.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Zrušit</AlertDialogCancel><AlertDialogAction className="danger-button" onClick={()=>void remove()}>Odstranit</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}

function MemberDetail({member,editing,onEditing,onSave,onDelete,onClose,notify}:{member:MemberRow|null;editing:boolean;onEditing:(value:boolean)=>void;onSave:(member:MemberRow)=>Promise<void>;onDelete:(member:MemberRow)=>Promise<void>;onClose:()=>void;notify:(message:string)=>void}) {
  const [draftMember,setDraftMember] = useState<MemberRow>(()=>member?[...member] as MemberRow:['','Hasič','Neuvedeno','Hasič','Ne','']);
  const [confirmDelete,setConfirmDelete] = useState(false);
  const role = member?.[1] ?? '';
  const permissions = member?.[3].split(' · ') ?? [];
  const medicalDate=member?.[2]&&member[2]!=='Neuvedeno'?member[2].split('.').reverse().join('-'):null;
  const medicalProblem = medicalDate ? new Date(`${medicalDate}T23:59:59`) < new Date() : false;
  const updateField=(index:number,value:string)=>setDraftMember(current=>current.map((field,i)=>i===index?value:field) as MemberRow);
  const updatePermission=(permission:string,checked:boolean)=>setDraftMember(current=>{const next=current[3]?current[3].split(' · '):[];const updated=checked?[...new Set([...next,permission])]:next.filter(item=>item!==permission);return current.map((field,i)=>i===3?updated.join(' · '):field) as MemberRow});
  const cancelEdit=()=>{if(!member?.[5]){onClose();return}setDraftMember([...member] as MemberRow);onEditing(false)};
  const saveEdit=async()=>{if(!draftMember[0].trim()){notify('Jméno člena nesmí být prázdné.');return}try{await onSave([...draftMember] as MemberRow);onEditing(false)}catch{}}
  return <Sheet open={!!member} onOpenChange={(open)=>{if(!open)onClose()}}><SheetContent className="member-sheet">
    <SheetHeader className="member-sheet-header"><div className="member-avatar-large">{member?.[0].split(' ').map(p=>p[0]).join('').slice(0,2)}</div><div><SheetTitle>{member?.[0]}</SheetTitle><SheetDescription>{role} · aktivní člen</SheetDescription></div></SheetHeader>
    {member && <div className="member-detail-body">
      {editing ? <div className="member-edit-form"><label>Jméno<input value={draftMember[0]} onChange={e=>updateField(0,e.target.value)}/></label><label>Hlavní funkce<select value={draftMember[1]} onChange={e=>updateField(1,e.target.value)}><option>Velitel jednotky</option><option>Velitel družstva</option><option>Strojník</option><option>Hasič</option><option>Neurčeno</option></select></label><label>Platnost zdravotní<input value={draftMember[2]} onChange={e=>updateField(2,e.target.value)}/></label><div className="edit-checks"><label><input type="checkbox" checked={draftMember[3].split(' · ').includes('Velitel')} onChange={e=>updatePermission('Velitel',e.target.checked)}/> Velitel</label><label><input type="checkbox" checked={draftMember[3].split(' · ').includes('Strojník')} onChange={e=>updatePermission('Strojník',e.target.checked)}/> Strojník</label><label><input type="checkbox" checked={draftMember[3].split(' · ').includes('Hasič')} onChange={e=>updatePermission('Hasič',e.target.checked)}/> Hasič</label><label><input type="checkbox" checked={draftMember[4]==='Ano'} onChange={e=>updateField(4,e.target.checked?'Ano':'Ne')}/> Nositel DT</label></div></div> : <>
        <section className="detail-section"><span className="section-kicker">Kvalifikace</span><div className="qualification-grid">{['Velitel','Strojník','Hasič'].map(q=><div key={q}><span>{q}</span><strong className={permissions.includes(q)?'yes':'no'}>{permissions.includes(q)?'✓ Ano':'— Ne'}</strong></div>)}<div><span>Nositel DT</span><strong className={member[4]==='Ano'?'yes':'no'}>{member[4]==='Ano'?'✓ Ano':'— Ne'}</strong></div></div></section>
        <section className="detail-section"><span className="section-kicker">Zdravotní prohlídka</span><div className={`medical-detail ${medicalProblem?'problem':''}`}><HeartPulse size={19}/><span><small>Platná do</small><strong>{member[2]}</strong></span><Badge className={medicalProblem?'medical-badge-bad':member[2]==='Neuvedeno'?'':'status-badge'}>{medicalProblem?'Po platnosti':member[2]==='Neuvedeno'?'Bez údaje':'Platná'}</Badge></div></section>
        <section className="detail-section"><span className="section-kicker">Dostupnost</span><div className="availability-detail"><span className="status-dot ok"/><span><strong>Dostupný</strong><small>Nemá evidovanou překážku pro aktuální týden.</small></span></div></section>
        <section className="detail-section"><span className="section-kicker">Historie služeb</span><div className="history-numbers"><div><strong>0</strong><span>Celkem</span></div><div><strong>0</strong><span>Velitel</span></div><div><strong>0</strong><span>Strojník</span></div><div><strong>0</strong><span>Hasič</span></div></div><p className="last-service">Historie se načte po první potvrzené službě.</p></section>
      </>}
    </div>}
    <SheetFooter className="member-sheet-footer">{editing?<><Button variant="outline" onClick={cancelEdit}>Zrušit</Button><Button className="primary-action compact" onClick={()=>void saveEdit()}>Uložit změny</Button></>:<>{member?.[5]&&<Button variant="outline" className="delete-action" onClick={()=>setConfirmDelete(true)}>Deaktivovat</Button>}<Button variant="outline" onClick={()=>notify(`Přidání nedostupnosti pro ${member?.[0]} je dostupné v sekci Nedostupnost.`)}>Přidat nedostupnost</Button><Button className="primary-action compact" onClick={()=>{setDraftMember(member?[...member] as MemberRow:['','Hasič','Neuvedeno','Hasič','Ne','']);onEditing(true)}}>Upravit člena</Button></>}</SheetFooter>
    <AlertDialog open={confirmDelete} onOpenChange={setConfirmDelete}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Deaktivovat člena?</AlertDialogTitle><AlertDialogDescription>Člen zmizí z aktivní evidence a nebude zařazován do služeb. Historické záznamy zůstanou zachované.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Zrušit</AlertDialogCancel><AlertDialogAction className="danger-button" onClick={()=>member&&void onDelete(member)}>Deaktivovat</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </SheetContent></Sheet>;
}
