'use client';

import { useMemo, useState } from 'react';
import { CalendarDays, Check, Gauge, RefreshCw, Share2, Trash2 } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import type { MemberRow } from '@/lib/member-data';
import { formatServiceDateTime, nextServiceWeek, planningServiceWeek, type ServiceTimeSettings } from '@/lib/service';
import type { DashboardService } from '@/lib/weekly-service-data';
import { buildMonthlyWhatsAppMessage, createWhatsAppShareUrl } from '@/lib/whatsapp';

type Props={settings:ServiceTimeSettings;members:MemberRow[];initialService:DashboardService|null;onServiceChange:(service:DashboardService|null)=>void;onShare:(service:DashboardService)=>void;notify:(message:string)=>void};
type Interval={from:string;to:string};

const monthValue=(date=new Date(),timeZone='Europe/Prague')=>new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit'}).format(date);
const monthTitle=(value:string)=>{const [year,month]=value.split('-').map(Number);return new Intl.DateTimeFormat('cs-CZ',{month:'long',year:'numeric',timeZone:'Europe/Prague'}).format(new Date(Date.UTC(year,month-1,2)));};

export function WeeklyPlanningModule({settings,members,initialService,onServiceChange,onShare,notify}:Props){
  const initialInterval=initialService?{start:new Date(initialService.from),end:new Date(initialService.to)}:planningServiceWeek(new Date(),settings);
  const [mode,setMode]=useState<'week'|'month'>('week'),[week,setWeek]=useState<Interval>({from:initialInterval.start.toISOString(),to:initialInterval.end.toISOString()}),[service,setService]=useState(initialService),[busy,setBusy]=useState(false),[monthDialog,setMonthDialog]=useState(false),[month,setMonth]=useState(monthValue(new Date(),settings.timezone)),[monthServices,setMonthServices]=useState<DashboardService[]>([]),[monthIntervals,setMonthIntervals]=useState<Interval[]>([]),[monthErrors,setMonthErrors]=useState<{from:string;error:string}[]>([]);
  const memberOptions=useMemo(()=>members.map(item=>({id:item[5],name:item[0]})),[members]);
  const publish=(next:DashboardService|null)=>{setService(next);const now=new Date();if(next&&new Date(next.from)<=now&&now<new Date(next.to))onServiceChange(next)};
  const loadWeek=async(reference:Date)=>{setBusy(true);try{const response=await fetch(`/api/services?reference=${encodeURIComponent(reference.toISOString())}`),body=await response.json();if(!response.ok)throw new Error(body.error);setWeek(body.interval);publish(body.service??null);setMode('week')}catch(error){notify(error instanceof Error?error.message:'Týden se nepodařilo načíst.')}finally{setBusy(false)}};
  const generate=async(reference=new Date(week.from))=>{setBusy(true);try{const response=await fetch('/api/services/generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({reference:reference.toISOString()})}),body=await response.json();if(!response.ok)throw new Error(body.error);setWeek({from:body.service.from,to:body.service.to});publish(body.service);notify(service?'Týden byl přelosován.':'Návrh příští služby byl vytvořen.');if(mode==='month')await loadMonth(month)}catch(error){notify(error instanceof Error?error.message:'Posádku se nepodařilo sestavit.')}finally{setBusy(false)}};
  const confirm=async(target:DashboardService)=>{setBusy(true);try{const response=await fetch(`/api/services/${target.id}/confirm`,{method:'POST'}),body=await response.json();if(!response.ok)throw new Error(body.error);publish(body.service);setMonthServices(items=>items.map(item=>item.id===body.service.id?body.service:item));notify('Týdenní posádka byla potvrzena.')}catch(error){notify(error instanceof Error?error.message:'Posádku se nepodařilo potvrdit.')}finally{setBusy(false)}};
  const loadMonth=async(value=month)=>{setBusy(true);try{const response=await fetch(`/api/services?month=${value}`),body=await response.json();if(!response.ok)throw new Error(body.error);setMonthServices(body.services);setMonthIntervals(body.intervals);setMonthErrors([]);setMode('month')}catch(error){notify(error instanceof Error?error.message:'Měsíční plán se nepodařilo načíst.')}finally{setBusy(false)}};
  const createMonth=async()=>{setBusy(true);try{const response=await fetch('/api/services/month-plan',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({month})}),body=await response.json();if(!response.ok)throw new Error(body.error);setMonthServices(body.services);setMonthErrors(body.errors);setMonthDialog(false);setMode('month');notify(`Měsíční plán je připraven. Vytvořeno ${body.created} nových návrhů.`)}catch(error){notify(error instanceof Error?error.message:'Měsíční plán se nepodařilo vytvořit.')}finally{setBusy(false)}};
  const removeDraft=async(target:DashboardService)=>{if(!window.confirm('Opravdu odstranit tento návrh služby?'))return;setBusy(true);try{const response=await fetch(`/api/services/${target.id}`,{method:'DELETE'}),body=await response.json();if(!response.ok)throw new Error(body.error);setMonthServices(items=>items.filter(item=>item.id!==target.id));if(service?.id===target.id){setService(null);const now=new Date();if(new Date(target.from)<=now&&now<new Date(target.to))onServiceChange(null)}notify('Návrh služby byl odstraněn.')}catch(error){notify(error instanceof Error?error.message:'Návrh se nepodařilo odstranit.')}finally{setBusy(false)}};
  const rerollMember=async(target:DashboardService,role:string,slot:number)=>{setBusy(true);try{const response=await fetch(`/api/services/${target.id}/reroll-member`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({role,slot})}),body=await response.json();if(!response.ok)throw new Error(body.error);publish(body.service);setMonthServices(items=>items.map(item=>item.id===target.id?body.service:item));notify('Člen byl přelosován a posádka znovu ověřena.')}catch(error){notify(error instanceof Error?error.message:'Člena se nepodařilo přelosovat.')}finally{setBusy(false)}};
  const changeMember=async(target:DashboardService,role:string,slot:number,memberId:string,acknowledgeWarnings=false)=>{setBusy(true);try{const response=await fetch(`/api/services/${target.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({role,slot,memberId,acknowledgeWarnings})}),body=await response.json();if(response.status===409&&body.warnings&&!acknowledgeWarnings){if(window.confirm(`Člen nesplňuje běžná pravidla: ${body.warnings.join(', ')}. Přesto změnu uložit?`))return void changeMember(target,role,slot,memberId,true);return}if(!response.ok)throw new Error(body.error);publish(body.service);setMonthServices(items=>items.map(item=>item.id===target.id?body.service:item));notify('Člen byl změněn a celá posádka je platná.')}catch(error){notify(error instanceof Error?error.message:'Člena se nepodařilo změnit.')}finally{setBusy(false)}};
  const confirmMonth=async()=>{setBusy(true);try{const response=await fetch('/api/services/confirm-month',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({month})}),body=await response.json();if(!response.ok)throw new Error(body.error);setMonthServices(body.services);setMonthErrors(body.errors);notify(`Potvrzeno ${body.confirmed} služeb, neplatných ${body.errors.length}.`)}catch(error){notify(error instanceof Error?error.message:'Hromadné potvrzení se nepodařilo.')}finally{setBusy(false)}};
  const shareMonth=()=>{const confirmed=monthServices.filter(item=>item.status==='CONFIRMED'&&item.crew.length===4);if(!confirmed.length){notify('Měsíční plán zatím neobsahuje žádnou potvrzenou službu.');return}const message=buildMonthlyWhatsAppMessage(monthTitle(month),confirmed.map(item=>{const commander=item.crew.find(member=>member.roleKey==='COMMANDER')!,driver=item.crew.find(member=>member.roleKey==='DRIVER')!,firefighters=item.crew.filter(member=>member.roleKey==='FIREFIGHTER');return{from:formatServiceDateTime(new Date(item.from),settings.timezone).slice(0,10),to:formatServiceDateTime(new Date(item.to),settings.timezone).slice(0,10),commander:commander.name,driver:driver.name,firefighters:[firefighters[0].name,firefighters[1].name] as [string,string]}}));window.open(createWhatsAppShareUrl(message),'_blank','noopener,noreferrer')};
  const openDetail=(item:DashboardService)=>{setWeek({from:item.from,to:item.to});publish(item);setMode('week')};
  const interval={start:new Date(week.from),end:new Date(week.to)};
  if(mode==='month')return <div className="module-stack"><div className="module-title"><div><span className="section-kicker">Plánování dopředu</span><h2>{monthTitle(month)}</h2></div><div className="module-actions"><Button variant="outline" onClick={()=>setMode('week')}>Jeden týden</Button><Button variant="outline" onClick={shareMonth}><Share2 size={15}/> Sdílet měsíční plán</Button><Button className="primary-action compact" onClick={()=>setMonthDialog(true)}><CalendarDays size={16}/> Naplánovat měsíc</Button></div></div>{monthErrors.map(error=><div className="planning-error" key={error.from}>⚠ {formatServiceDateTime(new Date(error.from),settings.timezone)}: {error.error}</div>)}<div className="month-plan-grid">{monthIntervals.map(intervalItem=>{const item=monthServices.find(candidate=>candidate.from===intervalItem.from);return item?<WeekCard key={intervalItem.from} service={item} settings={settings} busy={busy} members={memberOptions} onDetail={()=>openDetail(item)} onReroll={()=>void generate(new Date(item.from))} onDelete={()=>void removeDraft(item)} onConfirm={()=>void confirm(item)} onShare={()=>onShare(item)} onRerollMember={(role,slot)=>void rerollMember(item,role,slot)} onChangeMember={(role,slot,id)=>void changeMember(item,role,slot,id)}/>:<article className="panel month-week-card" key={intervalItem.from}><div><strong>{formatServiceDateTime(new Date(intervalItem.from),settings.timezone)} → {formatServiceDateTime(new Date(intervalItem.to),settings.timezone)}</strong><span>Bez návrhu</span></div><Button disabled={busy} onClick={()=>void generate(new Date(intervalItem.from))}>Vytvořit návrh</Button></article>})}</div><div className="actions month-actions"><Button variant="outline" onClick={()=>setMonthDialog(true)}>Změnit měsíc</Button><Button className="primary-action compact" disabled={busy||!monthServices.some(item=>item.status==='DRAFT')} onClick={()=>void confirmMonth()}>Potvrdit všechny platné služby</Button></div><MonthDialog open={monthDialog} onOpenChange={setMonthDialog} month={month} onMonth={setMonth} busy={busy} onCreate={()=>void createMonth()}/></div>;
  return <div className="module-stack"><div className="module-title"><div><span className="section-kicker">Plánování 3+1</span><h2>Týdenní služba</h2></div><div className="module-actions"><Button variant="outline" onClick={()=>void loadWeek(planningServiceWeek(new Date(),settings).start)}>Dnes</Button><Button variant="outline" onClick={()=>void loadWeek(nextServiceWeek(new Date(),settings).start)}>Příští týden</Button><Button variant="outline" onClick={()=>setMonthDialog(true)}>Měsíční plán</Button><Button className="primary-action compact" disabled={busy} onClick={()=>void (service?.status==='DRAFT'?generate(new Date(service.from)):generate(nextServiceWeek(new Date(),settings).start))}>{service?.status==='DRAFT'?'Přelosovat celý týden':'Připravit příští týden'}</Button></div></div><div className="week-strip"><button disabled={busy} aria-label="Předchozí týden" onClick={()=>void loadWeek(new Date(interval.start.getTime()-60000))}>←</button><div><strong>{formatServiceDateTime(interval.start,settings.timezone)} → {formatServiceDateTime(interval.end,settings.timezone)}</strong><span>Pondělí 06:00 — pondělí 06:00</span></div><button disabled={busy} aria-label="Následující týden" onClick={()=>void loadWeek(nextServiceWeek(interval.start,settings).start)}>→</button></div>{service?<WeekCard service={service} settings={settings} busy={busy} members={memberOptions} onReroll={()=>void generate(new Date(service.from))} onDelete={()=>void removeDraft(service)} onConfirm={()=>void confirm(service)} onShare={()=>onShare(service)} onRerollMember={(role,slot)=>void rerollMember(service,role,slot)} onChangeMember={(role,slot,id)=>void changeMember(service,role,slot,id)}/>:<article className="panel"><div className="empty-absence"><CalendarDays/><strong>Pro tento týden není připravená služba</strong><span>Návrh se sestaví z aktuálních databázových údajů a pravidel férovosti.</span><Button className="primary-action compact" disabled={busy} onClick={()=>void generate()}>{busy?'Sestavuji…':'Vytvořit návrh'}</Button></div></article>}<MonthDialog open={monthDialog} onOpenChange={setMonthDialog} month={month} onMonth={setMonth} busy={busy} onCreate={()=>void createMonth()}/></div>;
}

function WeekCard({service,settings,busy,members,onDetail,onReroll,onDelete,onConfirm,onShare,onRerollMember,onChangeMember}:{service:DashboardService;settings:ServiceTimeSettings;busy:boolean;members:{id:string;name:string}[];onDetail?:()=>void;onReroll:()=>void;onDelete:()=>void;onConfirm:()=>void;onShare:()=>void;onRerollMember:(role:string,slot:number)=>void;onChangeMember:(role:string,slot:number,id:string)=>void}){return <article className="panel month-week-card"><div className="panel-head"><div><span className="section-kicker">{formatServiceDateTime(new Date(service.from),settings.timezone)} → {formatServiceDateTime(new Date(service.to),settings.timezone)}</span><h2>Posádka 3+1</h2></div><Badge className={service.status==='CONFIRMED'?'status-badge':''} variant={service.status==='DRAFT'?'outline':undefined}>{service.status==='CONFIRMED'?<><Check size={13}/> Potvrzena</>:'Návrh'}</Badge></div><div className="crew-list">{service.crew.map((member,index)=><div className="crew-row planning-crew-row" key={`${member.roleKey}-${member.slot}`}><span className={`role-index ${index===0?'lead':''}`}>{index+1}</span><div className="crew-copy"><span>{member.role}</span><strong>{member.name}</strong></div>{member.dt&&<span className="dt-tag"><Gauge size={14}/> DT</span>}{service.status==='DRAFT'&&<div className="crew-edit-actions"><select aria-label={`Změnit ${member.role}`} value={member.memberId} disabled={busy} onChange={event=>onChangeMember(member.roleKey,member.slot,event.target.value)}>{members.map(option=><option value={option.id} key={option.id}>{option.name}</option>)}</select><Button variant="ghost" size="sm" disabled={busy} onClick={()=>onRerollMember(member.roleKey,member.slot)} title="Přelosovat jednoho člena"><RefreshCw size={14}/></Button></div>}</div>)}</div><div className="validation-box"><Check size={18}/><div><strong>Posádka splňuje pravidla</strong><span>4 různé osoby · role 1+1+2 · oprávnění · zdraví · dostupnost · minimálně {settings.minimumDt} DT</span></div></div><div className="actions planning-card-actions">{onDetail&&<Button variant="outline" onClick={onDetail}>Detail</Button>}{service.status==='CONFIRMED'?<Button variant="outline" onClick={onShare}><Share2 size={14}/> Sdílet tento týden</Button>:<><Button variant="outline" disabled={busy} onClick={onReroll}><RefreshCw size={14}/> Přelosovat týden</Button><Button variant="outline" disabled={busy} onClick={onDelete}><Trash2 size={14}/> Smazat návrh</Button><Button className="primary-action compact" disabled={busy} onClick={onConfirm}>Potvrdit</Button></>}</div></article>}

function MonthDialog({open,onOpenChange,month,onMonth,busy,onCreate}:{open:boolean;onOpenChange:(open:boolean)=>void;month:string;onMonth:(month:string)=>void;busy:boolean;onCreate:()=>void}){return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="planning-dialog"><DialogHeader><DialogTitle>Naplánovat měsíc</DialogTitle><DialogDescription>Vytvoří návrhy všech služeb, jejichž pondělní začátek spadá do vybraného měsíce. Existující návrhy i potvrzené služby zůstanou zachované.</DialogDescription></DialogHeader><label className="planning-month-label">Měsíc<input type="month" value={month} onChange={event=>onMonth(event.target.value)}/></label><DialogFooter><Button variant="outline" onClick={()=>onOpenChange(false)}>Zrušit</Button><Button className="primary-action compact" disabled={busy||!month} onClick={onCreate}>{busy?'Vytvářím…':'Vytvořit návrh služeb'}</Button></DialogFooter></DialogContent></Dialog>}
