import { NextResponse } from 'next/server';
import { z } from 'zod';
import { requireAdminApi } from '@/lib/auth';
import { getPrisma } from '@/lib/prisma';
import { DEFAULT_SERVICE_SETTINGS, suggestReplacement, type Assignment, type Role } from '@/lib/service';
import { toPlanningCandidates } from '@/lib/service-candidates';
import { serializeWeeklyService } from '@/lib/weekly-service-data';
import { refreshHardUnavailabilityForMembers } from '@/lib/service-availability-server';
import { syncServiceReplacements } from '@/lib/service-replacements-server';

export const runtime='nodejs';
const schema=z.object({role:z.enum(['COMMANDER','DRIVER','FIREFIGHTER']),slot:z.number().int().min(1).max(2)});

export async function POST(request:Request,context:{params:Promise<{id:string}>}){if(!(await requireAdminApi()))return NextResponse.json({error:'Nepřihlášený přístup.'},{status:401});try{const {id}=await context.params,input=schema.parse(await request.json()),prisma=getPrisma(),[service,settings,members,history]=await Promise.all([prisma.weeklyService.findUnique({where:{id},include:{assignments:{orderBy:[{role:'asc'},{slot:'asc'}]}}}),prisma.settings.findUnique({where:{id:'default'}}),prisma.member.findMany({include:{unavailability:true}}),prisma.weeklyServiceAssignment.findMany({where:{service:{status:{in:['CONFIRMED','DRAFT']}}},select:{memberId:true,role:true,service:{select:{weekStart:true,status:true}}}})]);if(!service)return NextResponse.json({error:'Služba nebyla nalezena.'},{status:404});if(service.status==='CANCELLED')return NextResponse.json({error:'Zrušenou službu nelze přelosovat.'},{status:409});const candidates=toPlanningCandidates(members,history,service.weekStart),assignments:Assignment[]=service.assignments.map(item=>({role:item.role as Role,member:candidates.find(member=>member.id===item.memberId)!,mode:item.selectionMode})),index=service.assignments.findIndex(item=>item.role===input.role&&item.slot===input.slot);if(index<0)return NextResponse.json({error:'Pozice nebyla nalezena.'},{status:404});const result=suggestReplacement(assignments,index,candidates,service.weekStart,service.weekEnd,settings?.minimumDt??DEFAULT_SERVICE_SETTINGS.minimumDt);if(!result.candidate)return NextResponse.json({error:result.error},{status:422});const changed=service.assignments[index];await prisma.$transaction([prisma.serviceReplacement.deleteMany({where:{assignmentId:changed.id}}),prisma.weeklyServiceAssignment.update({where:{id:changed.id},data:{memberId:result.candidate.id,selectionMode:'AUTO',nameSnapshot:result.candidate.name,roleSnapshot:input.role,dtSnapshot:result.candidate.dt}}),prisma.auditLog.create({data:{action:'MEMBER_REROLLED',entity:'WeeklyService',entityId:id,description:`Pozice ${input.role} byla přelosována z ${changed.nameSnapshot} na ${result.candidate.name}; stav: ${service.status}.`,actor:'Administrátor'}})]);await syncServiceReplacements(id);await refreshHardUnavailabilityForMembers([...service.assignments.map(item=>item.memberId),result.candidate.id]);const updated=await prisma.weeklyService.findUniqueOrThrow({where:{id},include:{assignments:{orderBy:[{role:'asc'},{slot:'asc'}]},replacements:{include:{originalMember:true,replacementMember:true},orderBy:{from:'asc'}}}});return NextResponse.json({service:serializeWeeklyService(updated),updatedConfirmed:service.status==='CONFIRMED'});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Člena se nepodařilo přelosovat.'},{status:400});}}
