import { z } from 'zod';
import { activityDateValue, type DriverActivityRow, type DtActivityRow } from '@/lib/conditioning';

const optionalText=z.string().trim().max(500).optional().default('');
export const dtActivityInputSchema=z.object({memberId:z.string().min(1),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),type:z.enum(['CONDITIONING','INCIDENT']),cylinderNumber:z.string().trim().max(80).optional().default(''),carrierNumber:z.string().trim().max(80).optional().default(''),maskNumber:z.string().trim().max(80).optional().default(''),incidentReference:z.string().trim().max(160).optional().default(''),note:optionalText});
export const driverActivityInputSchema=z.object({memberId:z.string().min(1),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),type:z.enum(['CONDITIONING','INCIDENT']),vehicle:z.string().trim().min(1).max(160),kilometers:z.number().int().min(0).max(100000).nullable().optional().default(null),incidentReference:z.string().trim().max(160).optional().default(''),note:optionalText});
export const nullable=(value:string)=>value||null;
export function serializeDtActivity(activity:{id:string;memberId:string;date:Date;type:string;cylinderNumber:string|null;carrierNumber:string|null;maskNumber:string|null;incidentReference:string|null;note:string|null}):DtActivityRow{return{id:activity.id,memberId:activity.memberId,date:activityDateValue(activity.date),type:activity.type==='INCIDENT'?'INCIDENT':'CONDITIONING',cylinderNumber:activity.cylinderNumber??'',carrierNumber:activity.carrierNumber??'',maskNumber:activity.maskNumber??'',incidentReference:activity.incidentReference??'',note:activity.note??''};}
export function serializeDriverActivity(activity:{id:string;memberId:string;date:Date;type:string;vehicle:string;kilometers:number|null;incidentReference:string|null;note:string|null}):DriverActivityRow{return{id:activity.id,memberId:activity.memberId,date:activityDateValue(activity.date),type:activity.type==='INCIDENT'?'INCIDENT':'CONDITIONING',vehicle:activity.vehicle,kilometers:activity.kilometers,incidentReference:activity.incidentReference??'',note:activity.note??''};}
