export type ActivityType='CONDITIONING'|'INCIDENT';
export type DtActivityRow={id:string;memberId:string;date:string;type:ActivityType;cylinderNumber:string;carrierNumber:string;maskNumber:string;incidentReference:string;note:string};
export type DriverActivityRow={id:string;memberId:string;date:string;type:ActivityType;vehicle:string;kilometers:number|null;incidentReference:string;note:string};
export type ConditioningMember={id:string;name:string;dt:boolean;canDrive:boolean;medicalValidUntil?:string|null;systemAccount?:boolean};
export type ConditioningData={members:ConditioningMember[];dtActivities:DtActivityRow[];driverActivities:DriverActivityRow[];warningDays:number};

const dateOnly=(date:Date)=>new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate(),12));
export function parseActivityDate(value:string){const match=/^(\d{4})-(\d{2})-(\d{2})$/.exec(value);if(!match)throw new Error('Datum musí být ve formátu RRRR-MM-DD.');const date=new Date(Date.UTC(Number(match[1]),Number(match[2])-1,Number(match[3]),12));if(date.getUTCFullYear()!==Number(match[1])||date.getUTCMonth()!==Number(match[2])-1||date.getUTCDate()!==Number(match[3]))throw new Error('Datum není platné.');return date;}
export function activityDateValue(date:Date){return`${date.getUTCFullYear()}-${String(date.getUTCMonth()+1).padStart(2,'0')}-${String(date.getUTCDate()).padStart(2,'0')}`;}
export function formatActivityDate(date:Date){return`${String(date.getUTCDate()).padStart(2,'0')}.${String(date.getUTCMonth()+1).padStart(2,'0')}.${date.getUTCFullYear()}`;}
export function addCalendarMonths(date:Date,months:number){const source=dateOnly(date),year=source.getUTCFullYear(),month=source.getUTCMonth()+months,day=source.getUTCDate();const targetYear=year+Math.floor(month/12),targetMonth=((month%12)+12)%12,lastDay=new Date(Date.UTC(targetYear,targetMonth+1,0,12)).getUTCDate();return new Date(Date.UTC(targetYear,targetMonth,Math.min(day,lastDay),12));}
export function pragueMonth(date:Date){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Prague',year:'numeric',month:'2-digit'}).formatToParts(date).reduce<Record<string,string>>((result,part)=>(result[part.type]=part.value,result),{});return{year:Number(parts.year),month:Number(parts.month)};}
function pragueDateOnly(date:Date){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Prague',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date).reduce<Record<string,string>>((result,part)=>(result[part.type]=part.value,result),{});return new Date(Date.UTC(Number(parts.year),Number(parts.month)-1,Number(parts.day),12));}
export function czechMonthLabel(date:Date){return new Intl.DateTimeFormat('cs-CZ',{timeZone:'Europe/Prague',month:'long',year:'numeric'}).format(date);}
export function latestDtActivity(memberId:string,activities:DtActivityRow[]){return activities.filter(activity=>activity.memberId===memberId).sort((left,right)=>right.date.localeCompare(left.date))[0]??null;}
export function latestDriverActivity(memberId:string,activities:DriverActivityRow[]){return activities.filter(activity=>activity.memberId===memberId).sort((left,right)=>right.date.localeCompare(left.date))[0]??null;}
export function dtDuty(member:ConditioningMember,activities:DtActivityRow[],now=new Date(),warningDays=30){if(!member.dt)return null;const last=latestDtActivity(member.id,activities);if(!last)return{last:null,due:null,days:null,status:'missing' as const};const due=addCalendarMonths(parseActivityDate(last.date),3),today=pragueDateOnly(now),days=Math.ceil((due.getTime()-today.getTime())/86400000);return{last,due:activityDateValue(due),days,status:days<0?'expired' as const:days<=warningDays?'warning' as const:'ok' as const};}
export function driverDuty(member:ConditioningMember,activities:DriverActivityRow[],now=new Date()){if(!member.canDrive)return null;const current=pragueMonth(now),currentActivity=activities.filter(activity=>{if(activity.memberId!==member.id)return false;const date=parseActivityDate(activity.date);return date.getUTCFullYear()===current.year&&date.getUTCMonth()+1===current.month;}).sort((left,right)=>right.date.localeCompare(left.date))[0]??null;const nextDue=new Date(Date.UTC(current.year,current.month+1,0,12));return{fulfilled:currentActivity!==null,last:latestDriverActivity(member.id,activities),currentActivity,nextDue:activityDateValue(nextDue)};}
export function medicalDuty(member:ConditioningMember,now=new Date(),warningDays=60){if(!member.medicalValidUntil)return{validUntil:null,days:null,status:'missing' as const};const validUntil=parseActivityDate(member.medicalValidUntil),today=pragueDateOnly(now),days=Math.ceil((validUntil.getTime()-today.getTime())/86400000);return{validUntil:member.medicalValidUntil,days,status:days<0?'expired' as const:days<=warningDays?'warning' as const:'ok' as const};}
export function conditioningDutySummary(data:ConditioningData,now=new Date()){
  const members=data.members.filter(member=>!member.systemAccount);
  return{
    dt:members.filter(member=>member.dt).map(member=>{const duty=dtDuty(member,data.dtActivities,now,data.warningDays)!;return{name:member.name,status:duty.status,last:duty.last?.date??null,due:duty.due,days:duty.days};}),
    drivers:members.filter(member=>member.canDrive).map(member=>{const duty=driverDuty(member,data.driverActivities,now)!;return{name:member.name,fulfilled:duty.fulfilled,date:duty.currentActivity?.date??null,vehicle:duty.currentActivity?.vehicle?.trim()||null,nextDue:duty.nextDue};}),
    medical:members.map(member=>{const duty=medicalDuty(member,now);return{name:member.name,...duty};}),
    monthLabel:czechMonthLabel(now),
  };
}
export function conditioningAttention(data:ConditioningData,now=new Date()){const dt=data.members.map(member=>({member,duty:dtDuty(member,data.dtActivities,now,data.warningDays)})).filter(item=>item.duty&&item.duty.status!=='ok');const drivers=data.members.map(member=>({member,duty:driverDuty(member,data.driverActivities,now)})).filter(item=>item.duty&&!item.duty.fulfilled);return{dt,drivers,monthLabel:czechMonthLabel(now)};}
