export type Role = 'COMMANDER' | 'DRIVER' | 'FIREFIGHTER';
export type Candidate = { id:string; name:string; active:boolean; system:boolean; reserveOnly:boolean; dt:boolean; medicalExam:Date|null; medicalValidUntil?:Date|null; roles:Role[]; serviceCount:number; lastService:Date|null; unavailable?:{from:Date;to:Date}[] };
export type Assignment = { role:Role; member:Candidate; mode:'AUTO'|'MANUAL' };
export type ServiceTimeSettings = { weekStartDay:number; weekStartHour:number; weekEndDay:number; weekEndHour:number; minimumDt:number; timezone:string };

export const DEFAULT_SERVICE_SETTINGS:ServiceTimeSettings={weekStartDay:1,weekStartHour:6,weekEndDay:0,weekEndHour:6,minimumDt:1,timezone:'Europe/Prague'};
export const MISSING_DT_ERROR='Pro tento časový interval nelze sestavit platnou posádku.\nChybí nositel dýchací techniky.';

const zoneParts=(date:Date,timeZone='Europe/Prague')=>new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',weekday:'short',hourCycle:'h23'}).formatToParts(date).reduce<Record<string,string>>((result,part)=>(result[part.type]=part.value,result),{});
const zoneOffsetMinutes=(date:Date,timeZone:string)=>{const value=new Intl.DateTimeFormat('en-US',{timeZone,timeZoneName:'longOffset'}).formatToParts(date).find(part=>part.type==='timeZoneName')?.value??'GMT';const match=/GMT([+-])(\d{2}):?(\d{2})?/.exec(value);if(!match)return 0;return (match[1]==='-'?-1:1)*(Number(match[2])*60+Number(match[3]??0));};
const zonedDate=(year:number,month:number,day:number,hour:number,minute=0,timeZone='Europe/Prague')=>{const guess=new Date(Date.UTC(year,month-1,day,hour,minute));const first=new Date(guess.getTime()-zoneOffsetMinutes(guess,timeZone)*60000);return new Date(guess.getTime()-zoneOffsetMinutes(first,timeZone)*60000);};
const shiftedDateParts=(year:number,month:number,day:number,days:number)=>{const value=new Date(Date.UTC(year,month-1,day+days));return{year:value.getUTCFullYear(),month:value.getUTCMonth()+1,day:value.getUTCDate()};};

export function serviceWeek(reference:Date,settings:ServiceTimeSettings=DEFAULT_SERVICE_SETTINGS){const parts=zoneParts(reference,settings.timezone),year=Number(parts.year),month=Number(parts.month),day=Number(parts.day);const weekday=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].indexOf(parts.weekday);const startCalendar=shiftedDateParts(year,month,day,-((weekday-settings.weekStartDay+7)%7));const start=zonedDate(startCalendar.year,startCalendar.month,startCalendar.day,settings.weekStartHour,0,settings.timezone);const durationDays=(settings.weekEndDay-settings.weekStartDay+7)%7;const endCalendar=shiftedDateParts(startCalendar.year,startCalendar.month,startCalendar.day,durationDays||7);const end=zonedDate(endCalendar.year,endCalendar.month,endCalendar.day,settings.weekEndHour,0,settings.timezone);return{start,end};}
export function nextServiceWeek(reference:Date,settings:ServiceTimeSettings=DEFAULT_SERVICE_SETTINGS){const current=serviceWeek(reference,settings);const parts=zoneParts(current.start,settings.timezone);const next=shiftedDateParts(Number(parts.year),Number(parts.month),Number(parts.day),7);const start=zonedDate(next.year,next.month,next.day,settings.weekStartHour,0,settings.timezone);return serviceWeek(new Date(start.getTime()+60000),settings);}
export function planningServiceWeek(reference:Date,settings:ServiceTimeSettings=DEFAULT_SERVICE_SETTINGS){const current=serviceWeek(reference,settings);return reference>=current.end?nextServiceWeek(reference,settings):current;}
export function wholeDay(reference:Date,timeZone='Europe/Prague'){const parts=zoneParts(reference,timeZone);const next=shiftedDateParts(Number(parts.year),Number(parts.month),Number(parts.day),1);return{start:zonedDate(Number(parts.year),Number(parts.month),Number(parts.day),0,0,timeZone),end:zonedDate(next.year,next.month,next.day,0,0,timeZone)};}
export function toLocalDateTimeInput(date:Date,timeZone='Europe/Prague'){const parts=zoneParts(date,timeZone);return`${parts.year}-${parts.month}-${parts.day}T${parts.hour}:${parts.minute}`;}
export function fromLocalDateTimeInput(value:string,timeZone='Europe/Prague'){const match=/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})$/.exec(value);if(!match)return null;return zonedDate(Number(match[1]),Number(match[2]),Number(match[3]),Number(match[4]),Number(match[5]),timeZone);}
export function formatServiceDateTime(date:Date,timeZone='Europe/Prague'){const parts=zoneParts(date,timeZone);return`${parts.day}.${parts.month}.${parts.year} ${parts.hour}:${parts.minute}`;}

export const intervalsOverlap=(aStart:Date,aEnd:Date,bStart:Date,bEnd:Date)=>aStart<bEnd&&bStart<aEnd;
export const medicalValidUntil=(exam:Date|null)=>exam?new Date(exam.getFullYear()+2,exam.getMonth(),exam.getDate(),23,59,59,999):null;
export const hasValidMedical=(member:Candidate,at:Date)=>{const stored=member.medicalValidUntil===undefined?medicalValidUntil(member.medicalExam):member.medicalValidUntil;const until=stored&&member.medicalValidUntil!==undefined?new Date(stored.getTime()+86400000-1):stored;return!!until&&until>=at;};
export function eligibility(member:Candidate,role:Role,start:Date,end:Date,manual=false){const reasons:string[]=[];if(!member.active)reasons.push('neaktivní člen');if(member.system)reasons.push('systémový účet');if(member.reserveOnly&&!manual)reasons.push('pouze na počet');if(!member.roles.includes(role))reasons.push('chybí oprávnění');if(!hasValidMedical(member,new Date(end.getTime()-1)))reasons.push('neplatná zdravotní prohlídka');if(member.unavailable?.some(unavailable=>intervalsOverlap(unavailable.from,unavailable.to,start,end)))reasons.push('nahlášená nedostupnost');return{eligible:reasons.length===0,reasons};}
export function weightedPick(candidates:Candidate[],random=Math.random){const weights=candidates.map(candidate=>Math.max(.15,1/(1+candidate.serviceCount*.18))*(candidate.lastService?Math.min(3,Math.max(.5,(Date.now()-candidate.lastService.getTime())/604800000)):3));let cursor=random()*weights.reduce((left,right)=>left+right,0);for(let index=0;index<candidates.length;index+=1){cursor-=weights[index];if(cursor<=0)return candidates[index];}return candidates.at(-1)!;}
export function validateCrew(assignments:Assignment[],minimumDt=1){const errors:string[]=[],ids=assignments.map(assignment=>assignment.member.id);if(assignments.length!==4)errors.push('Posádka musí mít přesně 4 členy.');if(new Set(ids).size!==ids.length)errors.push('Stejná osoba nesmí být použita dvakrát.');if(assignments.filter(assignment=>assignment.role==='COMMANDER').length!==1)errors.push('Chybí právě jeden velitel.');if(assignments.filter(assignment=>assignment.role==='DRIVER').length!==1)errors.push('Chybí právě jeden strojník.');if(assignments.filter(assignment=>assignment.role==='FIREFIGHTER').length!==2)errors.push('Posádka musí mít dva hasiče.');if(assignments.filter(assignment=>assignment.member.dt).length<minimumDt)errors.push(MISSING_DT_ERROR);return{valid:errors.length===0,errors};}
export function assembleCrew(candidates:Candidate[],start:Date,end:Date,random=Math.random,minimumDt=1):Assignment[]|null{const roles:Role[]=['COMMANDER','DRIVER','FIREFIGHTER','FIREFIGHTER'];let result:Assignment[]|null=null;const search=(index:number,used:Set<string>,picked:Assignment[])=>{if(index===roles.length){if(validateCrew(picked,minimumDt).valid)result=[...picked];return;}const role=roles[index],pool=candidates.filter(candidate=>!used.has(candidate.id)&&eligibility(candidate,role,start,end).eligible),ordered=[...pool].map(candidate=>({candidate,tie:random()})).sort((left,right)=>left.candidate.serviceCount-right.candidate.serviceCount||(left.candidate.lastService?.getTime()??0)-(right.candidate.lastService?.getTime()??0)||left.tie-right.tie).map(item=>item.candidate);for(const member of ordered){used.add(member.id);picked.push({role,member,mode:'AUTO'});search(index+1,used,picked);if(result)return;picked.pop();used.delete(member.id);}};search(0,new Set(),[]);return result;}
export function replacementCandidates(assignments:Assignment[],replacedIndex:number,candidates:Candidate[],start:Date,end:Date,minimumDt=1){const replaced=assignments[replacedIndex];if(!replaced)return[];const remaining=assignments.filter((_,index)=>index!==replacedIndex);const used=new Set(remaining.map(assignment=>assignment.member.id));used.add(replaced.member.id);return candidates.filter(candidate=>!used.has(candidate.id)&&eligibility(candidate,replaced.role,start,end).eligible).filter(candidate=>validateCrew([...remaining,{role:replaced.role,member:candidate,mode:'AUTO'}],minimumDt).valid);}
export function suggestReplacement(assignments:Assignment[],replacedIndex:number,candidates:Candidate[],start:Date,end:Date,minimumDt=1,random=Math.random){const valid=replacementCandidates(assignments,replacedIndex,candidates,start,end,minimumDt);if(valid.length)return{candidate:weightedPick(valid,random),error:null};const replaced=assignments[replacedIndex],remaining=assignments.filter((_,index)=>index!==replacedIndex),used=new Set(remaining.map(assignment=>assignment.member.id));if(replaced)used.add(replaced.member.id);const otherwiseEligible=replaced?candidates.filter(candidate=>!used.has(candidate.id)&&eligibility(candidate,replaced.role,start,end).eligible):[];const dtShortage=otherwiseEligible.some(candidate=>validateCrew([...remaining,{role:replaced.role,member:candidate,mode:'AUTO'}],minimumDt).errors.includes(MISSING_DT_ERROR));return{candidate:null,error:dtShortage?MISSING_DT_ERROR:'Pro tento časový interval nelze sestavit platnou posádku.'};}
