export type Role = 'COMMANDER' | 'DRIVER' | 'FIREFIGHTER';
export type Candidate = { id:string; name:string; active:boolean; system:boolean; reserveOnly:boolean; dt:boolean; medicalExam:Date|null; roles:Role[]; serviceCount:number; lastService:Date|null; unavailable?:{from:Date;to:Date}[] };
export type Assignment = { role:Role; member:Candidate; mode:'AUTO'|'MANUAL' };

const pragueParts=(date:Date)=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Prague',year:'numeric',month:'2-digit',day:'2-digit',weekday:'short'}).formatToParts(date).reduce<Record<string,string>>((a,p)=>(a[p.type]=p.value,a),{});
const pragueDate=(year:number,month:number,day:number,hour=6)=>{const guess=new Date(Date.UTC(year,month-1,day,hour));const zone=new Intl.DateTimeFormat('en-US',{timeZone:'Europe/Prague',timeZoneName:'shortOffset'}).formatToParts(guess).find(p=>p.type==='timeZoneName')?.value??'GMT';const offset=Number(zone.replace('GMT','').split(':')[0]||0);return new Date(Date.UTC(year,month-1,day,hour-offset));};
export function serviceWeek(reference:Date){const p=pragueParts(reference),y=+p.year,m=+p.month,d=+p.day;const weekday=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].indexOf(p.weekday),shift=(weekday+6)%7;const s=new Date(Date.UTC(y,m-1,d-shift)),e=new Date(Date.UTC(y,m-1,d-shift+6));return{start:pragueDate(s.getUTCFullYear(),s.getUTCMonth()+1,s.getUTCDate()),end:pragueDate(e.getUTCFullYear(),e.getUTCMonth()+1,e.getUTCDate())};}
export const intervalsOverlap=(aStart:Date,aEnd:Date,bStart:Date,bEnd:Date)=>aStart<bEnd&&bStart<aEnd;
export const medicalValidUntil=(exam:Date|null)=>exam?new Date(exam.getFullYear()+2,exam.getMonth(),exam.getDate(),23,59,59,999):null;
export const hasValidMedical=(member:Candidate,at:Date)=>{const until=medicalValidUntil(member.medicalExam);return!!until&&until>=at;};
export function eligibility(member:Candidate,role:Role,start:Date,end:Date,manual=false){const reasons:string[]=[];if(!member.active)reasons.push('neaktivní člen');if(member.system)reasons.push('systémový účet');if(member.reserveOnly&&!manual)reasons.push('pouze na počet');if(!member.roles.includes(role))reasons.push('chybí oprávnění');if(!hasValidMedical(member,start))reasons.push('neplatná zdravotní prohlídka');if(member.unavailable?.some(u=>intervalsOverlap(u.from,u.to,start,end)))reasons.push('nahlášená nedostupnost');return{eligible:reasons.length===0,reasons};}
export function weightedPick(candidates:Candidate[],random=Math.random){const weights=candidates.map(c=>Math.max(.15,1/(1+c.serviceCount*.18))*(c.lastService?Math.min(3,Math.max(.5,(Date.now()-c.lastService.getTime())/604800000)):3));let cursor=random()*weights.reduce((a,b)=>a+b,0);for(let i=0;i<candidates.length;i++){cursor-=weights[i];if(cursor<=0)return candidates[i];}return candidates.at(-1)!;}
export function validateCrew(assignments:Assignment[],minimumDt=1){const errors:string[]=[],ids=assignments.map(a=>a.member.id);if(assignments.length!==4)errors.push('Posádka musí mít přesně 4 členy.');if(new Set(ids).size!==ids.length)errors.push('Stejná osoba nesmí být použita dvakrát.');if(assignments.filter(a=>a.role==='COMMANDER').length!==1)errors.push('Chybí právě jeden velitel.');if(assignments.filter(a=>a.role==='DRIVER').length!==1)errors.push('Chybí právě jeden strojník.');if(assignments.filter(a=>a.role==='FIREFIGHTER').length!==2)errors.push('Posádka musí mít dva hasiče.');if(assignments.filter(a=>a.member.dt).length<minimumDt)errors.push(`Posádka musí obsahovat minimálně ${minimumDt} nositele DT.`);return{valid:errors.length===0,errors};}
export function assembleCrew(candidates:Candidate[],start:Date,end:Date,random=Math.random){const roles:Role[]=['COMMANDER','DRIVER','FIREFIGHTER','FIREFIGHTER'];let result:Assignment[]|null=null;const search=(index:number,used:Set<string>,picked:Assignment[])=>{if(index===roles.length){if(validateCrew(picked).valid)result=[...picked];return;}const role=roles[index],pool=candidates.filter(c=>!used.has(c.id)&&eligibility(c,role,start,end).eligible),ordered=[...pool].sort(()=>random()-.5).sort((a,b)=>Number(b.dt)-Number(a.dt));for(const member of ordered){used.add(member.id);picked.push({role,member,mode:'AUTO'});search(index+1,used,picked);if(result)return;picked.pop();used.delete(member.id);}};search(0,new Set(),[]);return result;}
