import { NextResponse } from 'next/server';
import { requireAdminApi } from '@/lib/auth';
import { recurringUnavailabilityInputSchema } from '@/lib/member-data';
import { getPrisma } from '@/lib/prisma';
import { syncServiceReplacements } from '@/lib/service-replacements-server';

export const runtime='nodejs';
const serialize=(item:{id:string;memberId:string;anchorStart:Date;durationMinutes:number;intervalMinutes:number;reason:string|null;member:{firstName:string;lastName:string}})=>({id:item.id,memberId:item.memberId,member:`${item.member.firstName} ${item.member.lastName==='—'?'':item.member.lastName}`.trim(),anchorStart:item.anchorStart.toISOString(),durationMinutes:item.durationMinutes,intervalMinutes:item.intervalMinutes,reason:item.reason??''});
async function affected(memberId:string){const prisma=getPrisma(),services=await prisma.weeklyService.findMany({where:{assignments:{some:{memberId}},weekEnd:{gt:new Date()}},select:{id:true}});for(const service of services)await syncServiceReplacements(service.id);}
export async function PATCH(request:Request,context:{params:Promise<{id:string}>}){if(!(await requireAdminApi()))return NextResponse.json({error:'Nepřihlášený přístup.'},{status:401});try{const {id}=await context.params,input=recurringUnavailabilityInputSchema.parse(await request.json()),prisma=getPrisma(),previous=await prisma.recurringUnavailability.findUniqueOrThrow({where:{id}}),record=await prisma.$transaction(async tx=>{const updated=await tx.recurringUnavailability.update({where:{id},data:{memberId:input.memberId,anchorStart:new Date(input.anchorStart),durationMinutes:input.durationMinutes,intervalMinutes:input.intervalMinutes,reason:input.reason||null},include:{member:true}});await tx.auditLog.create({data:{action:'RECURRING_UNAVAILABILITY_UPDATED',entity:'RecurringUnavailability',entityId:id,description:'Opakovaná pracovní směna byla upravena.',actor:'Administrátor'}});return updated;});await affected(previous.memberId);if(previous.memberId!==input.memberId)await affected(input.memberId);return NextResponse.json({record:serialize(record)});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Opakovanou směnu se nepodařilo upravit.'},{status:400});}}
export async function DELETE(_request:Request,context:{params:Promise<{id:string}>}){if(!(await requireAdminApi()))return NextResponse.json({error:'Nepřihlášený přístup.'},{status:401});try{const {id}=await context.params,prisma=getPrisma(),record=await prisma.recurringUnavailability.findUniqueOrThrow({where:{id}});await prisma.$transaction([prisma.recurringUnavailability.delete({where:{id}}),prisma.auditLog.create({data:{action:'RECURRING_UNAVAILABILITY_DELETED',entity:'RecurringUnavailability',entityId:id,description:'Opakovaná pracovní směna byla odstraněna.',actor:'Administrátor'}})]);await affected(record.memberId);return NextResponse.json({ok:true});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Opakovanou směnu se nepodařilo odstranit.'},{status:400});}}
