import { NextResponse } from 'next/server';
import { z } from 'zod';
import { requireAdminApi } from '@/lib/auth';
import { getPrisma } from '@/lib/prisma';
import { DEFAULT_SERVICE_SETTINGS, eligibility, intervalsOverlap, validateCrew, type Assignment, type Candidate, type Role } from '@/lib/service';
import { serializeWeeklyService } from '@/lib/weekly-service-data';

export const runtime='nodejs';
const patchSchema=z.object({role:z.enum(['COMMANDER','DRIVER','FIREFIGHTER']),slot:z.number().int().min(1).max(2),memberId:z.string().min(1),acknowledgeWarnings:z.boolean().default(false)});
const candidate=(member:{id:string;firstName:string;lastName:string;active:boolean;systemAccount:boolean;reserveOnly:boolean;dt:boolean;medicalExamAt:Date|null;medicalValidUntil:Date|null;canCommand:boolean;canDrive:boolean;canFight:boolean;unavailability:{from:Date;to:Date}[]}):Candidate=>({id:member.id,name:`${member.firstName} ${member.lastName==='—'?'':member.lastName}`.trim(),active:member.active,system:member.systemAccount,reserveOnly:member.reserveOnly,dt:member.dt,medicalExam:member.medicalExamAt,medicalValidUntil:member.medicalValidUntil,roles:[member.canCommand&&'COMMANDER',member.canDrive&&'DRIVER',member.canFight&&'FIREFIGHTER'].filter(Boolean) as Role[],serviceCount:0,lastService:null,unavailable:member.unavailability});

export async function PATCH(request:Request,context:{params:Promise<{id:string}>}){if(!(await requireAdminApi()))return NextResponse.json({error:'Nepřihlášený přístup.'},{status:401});try{const {id}=await context.params,input=patchSchema.parse(await request.json()),prisma=getPrisma(),[service,settings,member]=await Promise.all([prisma.weeklyService.findUnique({where:{id},include:{assignments:{include:{member:{include:{unavailability:true}}}}}}),prisma.settings.findUnique({where:{id:'default'}}),prisma.member.findUnique({where:{id:input.memberId},include:{unavailability:true}})]);if(!service||service.status==='CONFIRMED')return NextResponse.json({error:'Upravovat lze pouze návrh služby.'},{status:409});if(!member)return NextResponse.json({error:'Člen nebyl nalezen.'},{status:404});const selected=candidate(member),eligibilityResult=eligibility(selected,input.role,service.weekStart,service.weekEnd,true),warnings:string[]=[];if(member.reserveOnly)warnings.push('člen je veden pouze na počet');if(member.unavailability.some(item=>intervalsOverlap(item.from,item.to,service.weekStart,service.weekEnd)))warnings.push('člen je v tomto týdnu nedostupný');if(eligibilityResult.reasons.length)return NextResponse.json({error:eligibilityResult.reasons.join('\n')},{status:422});if(warnings.length&&!input.acknowledgeWarnings)return NextResponse.json({error:'Ruční změna vyžaduje potvrzení.',warnings},{status:409});const assignments:Assignment[]=service.assignments.map(item=>({role:item.role as Role,member:item.role===input.role&&item.slot===input.slot?selected:candidate(item.member),mode:'MANUAL'})),validation=validateCrew(assignments,settings?.minimumDt??DEFAULT_SERVICE_SETTINGS.minimumDt);if(!validation.valid)return NextResponse.json({error:validation.errors.join('\n')},{status:422});await prisma.$transaction([prisma.weeklyServiceAssignment.update({where:{serviceId_role_slot:{serviceId:id,role:input.role,slot:input.slot}},data:{memberId:member.id,selectionMode:'MANUAL',nameSnapshot:selected.name,roleSnapshot:input.role,dtSnapshot:selected.dt}}),prisma.auditLog.create({data:{action:'MEMBER_CHANGED',entity:'WeeklyService',entityId:id,description:`Člen na pozici ${input.role} byl ručně změněn.`,actor:'Administrátor'}})]);const updated=await prisma.weeklyService.findUniqueOrThrow({where:{id},include:{assignments:{orderBy:[{role:'asc'},{slot:'asc'}]}}});return NextResponse.json({service:serializeWeeklyService(updated),warnings});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Službu se nepodařilo upravit.'},{status:400});}}

export async function DELETE(_request:Request,context:{params:Promise<{id:string}>}){if(!(await requireAdminApi()))return NextResponse.json({error:'Nepřihlášený přístup.'},{status:401});try{const {id}=await context.params,prisma=getPrisma(),service=await prisma.weeklyService.findUnique({where:{id},select:{status:true}});if(!service)return NextResponse.json({error:'Služba nebyla nalezena.'},{status:404});if(service.status==='CONFIRMED')return NextResponse.json({error:'Potvrzenou službu nelze odstranit.'},{status:409});await prisma.$transaction([prisma.weeklyService.delete({where:{id}}),prisma.auditLog.create({data:{action:'WEEK_DRAFT_DELETED',entity:'WeeklyService',entityId:id,description:'Návrh týdenní služby byl odstraněn.',actor:'Administrátor'}})]);return NextResponse.json({ok:true});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Návrh se nepodařilo odstranit.'},{status:400});}}
