import { NextResponse } from 'next/server';
import { z } from 'zod';
import { requireAdminApi } from '@/lib/auth';
import { getPrisma } from '@/lib/prisma';
import { DEFAULT_FAIRNESS_SETTINGS, DEFAULT_SERVICE_SETTINGS, MISSING_DT_ERROR, assembleCrew, serviceWeeksForMonth, shouldCreateMonthDraft, type Role } from '@/lib/service';
import { toPlanningCandidates } from '@/lib/service-candidates';
import { serializeWeeklyService } from '@/lib/weekly-service-data';

export const runtime='nodejs';
const schema=z.object({month:z.string().regex(/^\d{4}-\d{2}$/)});

export async function POST(request:Request){if(!(await requireAdminApi()))return NextResponse.json({error:'Nepřihlášený přístup.'},{status:401});try{const {month}=schema.parse(await request.json()),prisma=getPrisma(),[settings,members,allHistory]=await Promise.all([prisma.settings.findUnique({where:{id:'default'}}),prisma.member.findMany({include:{unavailability:true}}),prisma.weeklyServiceAssignment.findMany({where:{service:{status:{in:['CONFIRMED','DRAFT']}}},select:{memberId:true,role:true,service:{select:{weekStart:true}}}})]),rules=settings?{weekStartDay:settings.weekStartDay,weekStartHour:settings.weekStartHour,weekEndDay:settings.weekEndDay,weekEndHour:settings.weekEndHour,minimumDt:settings.minimumDt,timezone:settings.timezone}:DEFAULT_SERVICE_SETTINGS,fairness=settings?{fairDraw:settings.fairDraw,considerTotal:settings.considerTotal,considerRole:settings.considerRole,preferRested:settings.preferRested,allowConsecutive:settings.allowConsecutive}:DEFAULT_FAIRNESS_SETTINGS,intervals=serviceWeeksForMonth(month,rules),existing=await prisma.weeklyService.findMany({where:{weekStart:{in:intervals.map(item=>item.start)}},include:{assignments:true}}),history=[...allHistory],createdIds:string[]=[],errors:{from:string;error:string}[]=[];
    for(const interval of intervals){const saved=existing.find(item=>item.weekStart.getTime()===interval.start.getTime());if(!shouldCreateMonthDraft(saved?.status==='CONFIRMED'?'CONFIRMED':saved?.status==='DRAFT'?'DRAFT':null))continue;const candidates=toPlanningCandidates(members,history,interval.start),crew=assembleCrew(candidates,interval.start,interval.end,Math.random,rules.minimumDt,fairness);if(!crew){const withoutDt=assembleCrew(candidates,interval.start,interval.end,Math.random,0,fairness);errors.push({from:interval.start.toISOString(),error:withoutDt?MISSING_DT_ERROR:'Pro tento týden nelze sestavit platnou posádku z dostupných členů.'});continue;}const id=await prisma.$transaction(async tx=>{const service=await tx.weeklyService.create({data:{weekStart:interval.start,weekEnd:interval.end,status:'DRAFT'}}),slots=new Map<Role,number>();await tx.weeklyServiceAssignment.createMany({data:crew.map(assignment=>{const slot=(slots.get(assignment.role)??0)+1;slots.set(assignment.role,slot);return{serviceId:service.id,memberId:assignment.member.id,role:assignment.role,slot,selectionMode:'AUTO',nameSnapshot:assignment.member.name,roleSnapshot:assignment.role,dtSnapshot:assignment.member.dt};})});await tx.auditLog.create({data:{action:'WEEK_DRAFT_CREATED',entity:'WeeklyService',entityId:service.id,description:`Návrh služby byl vytvořen v měsíčním plánu ${month}.`,actor:'Administrátor'}});return service.id;});createdIds.push(id);history.push(...crew.map(assignment=>({memberId:assignment.member.id,role:assignment.role,service:{weekStart:interval.start}})));}
    await prisma.auditLog.create({data:{action:'MONTH_PLAN_CREATED',entity:'MonthlyPlan',entityId:month,description:`Měsíční plán ${month} byl vytvořen; nové návrhy: ${createdIds.length}.`,actor:'Administrátor'}});const services=await prisma.weeklyService.findMany({where:{weekStart:{in:intervals.map(item=>item.start)}},include:{assignments:{orderBy:[{role:'asc'},{slot:'asc'}]}},orderBy:{weekStart:'asc'}});return NextResponse.json({services:services.map(serializeWeeklyService),created:createdIds.length,errors});
  }catch(error){return NextResponse.json({error:error instanceof Error?error.message:'Měsíční plán se nepodařilo vytvořit.'},{status:400});}}
