import { NextResponse } from 'next/server';
import { requireAdminApi } from '@/lib/auth';
import { parseActivityDate } from '@/lib/conditioning';
import { dtActivityInputSchema, nullable, serializeDtActivity } from '@/lib/conditioning-data';
import { getPrisma } from '@/lib/prisma';

export const runtime='nodejs';
export async function PATCH(request:Request,context:{params:Promise<{id:string}>}){if(!(await requireAdminApi()))return NextResponse.json({error:'Nepřihlášený přístup.'},{status:401});try{const {id}=await context.params,input=dtActivityInputSchema.parse(await request.json()),prisma=getPrisma();const activity=await prisma.$transaction(async tx=>{const member=await tx.member.findUnique({where:{id:input.memberId},select:{dt:true,active:true,systemAccount:true}});if(!member?.active||!member.dt||member.systemAccount)throw new Error('DT událost lze zapsat pouze aktivnímu nositeli DT.');const updated=await tx.dtActivity.update({where:{id},data:{memberId:input.memberId,date:parseActivityDate(input.date),type:input.type,cylinderNumber:nullable(input.cylinderNumber),carrierNumber:nullable(input.carrierNumber),maskNumber:nullable(input.maskNumber),incidentReference:nullable(input.incidentReference),note:nullable(input.note)}});await tx.auditLog.create({data:{action:'UPDATE',entity:'DtActivity',entityId:id,description:'Událost dýchací techniky byla upravena.',actor:'Administrátor'}});return updated;});return NextResponse.json({activity:serializeDtActivity(activity)});}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'DT událost se nepodařilo upravit.'},{status:400});}}
export async function DELETE(_request:Request,context:{params:Promise<{id:string}>}){if(!(await requireAdminApi()))return NextResponse.json({error:'Nepřihlášený přístup.'},{status:401});const {id}=await context.params,prisma=getPrisma();await prisma.$transaction([prisma.dtActivity.delete({where:{id}}),prisma.auditLog.create({data:{action:'DELETE',entity:'DtActivity',entityId:id,description:'Událost dýchací techniky byla odstraněna.',actor:'Administrátor'}})]);return NextResponse.json({ok:true});}
